# Generated by Django 4.0.8 on 2022-11-24 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="A name for the folder", max_length=80),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_preference",
                    models.CharField(
                        choices=[
                            ("", "Not specified"),
                            ("INV", "Invoice adjustment"),
                            ("PB", "Pro bono"),
                            ("PPL", "PayPal"),
                            ("VNM", "Venmo"),
                            ("ZLL", "Zelle"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                ("paypal_username", models.CharField(max_length=128)),
                ("venmo_handle", models.CharField(max_length=128)),
                ("zelle_info", models.CharField(max_length=128)),
                (
                    "notes",
                    models.TextField(help_text="Any notes on payment or whatever."),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name of job", max_length=80)),
                (
                    "description",
                    models.TextField(
                        help_text="A job description of what you should do"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        help_text="When the job should be finished by"
                    ),
                ),
                (
                    "spades_bounty",
                    models.PositiveIntegerField(
                        help_text="How many spades the job is worth"
                    ),
                ),
                (
                    "usd_bounty",
                    models.PositiveIntegerField(
                        help_text="How many US dollars the job is worth"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Open"),
                            ("IP", "In progress"),
                            ("PRV", "Pending review"),
                            ("OK", "Completed"),
                        ],
                        default="NEW",
                        help_text="The current status of the job",
                        max_length=3,
                    ),
                ),
                (
                    "worker_deliverable",
                    models.TextField(
                        blank=True,
                        help_text="The worker can submit some deliverable here",
                    ),
                ),
                (
                    "worker_notes",
                    models.TextField(
                        blank=True, help_text="The worker can make some notes here"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The worker that is currently assigned.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.worker",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="This is the folder that the job goes under.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.jobfolder",
                    ),
                ),
            ],
        ),
    ]
