# Generated by Django 4.0.8 on 2022-12-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_remove_worker_payment_preference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfolder",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Whether to show this folder"
            ),
        ),
    ]
