# Generated by Django 4.0.8 on 2022-12-02 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_jobfolder_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfolder",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now,
                help_text="A slug for this job folder",
            ),
            preserve_default=False,
        ),
    ]
