# Generated by Django 4.0.8 on 2022-12-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_jobfolder_description_alter_job_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="spades_bounty",
            field=models.PositiveIntegerField(
                default=0, help_text="How many spades the job is worth"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="usd_bounty",
            field=models.PositiveIntegerField(
                default=0, help_text="How many US dollars the job is worth"
            ),
        ),
    ]
