# Generated by Django 4.0.8 on 2022-12-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_alter_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="payment_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not specified"),
                    ("INV", "Invoice adjustment"),
                    ("PB", "Pro bono"),
                    ("PPL", "PayPal"),
                    ("VNM", "Venmo"),
                    ("ZLL", "Zelle"),
                ],
                default="",
                max_length=3,
            ),
        ),
    ]
