# Generated by Django 4.0.8 on 2022-12-02 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_alter_job_payment_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
