# Generated by Django 4.0.8 on 2022-12-02 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_calendar_urls_again"),
        ("payments", "0014_alter_job_progress_alter_worker_google_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobfolder",
            name="semester",
        ),
        migrations.AddField(
            model_name="job",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.semester",
            ),
        ),
    ]
