# Generated by Django 4.0.8 on 2022-12-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_alter_job_usd_bounty"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
