# Generated by Django 4.0.8 on 2022-12-03 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_worker_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='twitch_username',
            field=models.CharField(blank=True, help_text='Username on Twitch.tv', max_length=128, validators=[django.core.validators.RegexValidator("^[-a-zA-Z0-9_'.]+$")]),
        ),
    ]
