# Generated by Django 4.0.8 on 2022-12-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_remove_worker_google_username_worker_gmail_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfolder',
            name='max_pending',
            field=models.IntegerField(blank=True, help_text='Maximum number of pending tasks that can be claimed total by one person.', null=True),
        ),
        migrations.AddField(
            model_name='jobfolder',
            name='max_total',
            field=models.IntegerField(blank=True, help_text='Maximum number of tasks that can be claimed total by one person, including completed ones.', null=True),
        ),
    ]
