# Generated by Django 4.0.8 on 2022-12-15 01:27

from django.db import migrations, models
from typing import Any

PROGRESS_CHOICES = (
    ("NEW", "JOB_NEW"),
    ("REV", "JOB_REV"),
    ("SUB", "JOB_SUB"),
    ("VFD", "JOB_VFD"),
)
PREF_CHOICES = (
    ("", "PREF_NONE"),
    ("INV", "PREF_INVCRD"),
    ("PB", "PREF_PROBONO"),
    ("VNM", "PREF_VENMO"),
    ("ZLL", "PREF_ZELLE"),
)


def update_fields(apps: Any, scheme_editor: Any):
    Job = apps.get_model('payments', 'job')
    for x, y in PROGRESS_CHOICES:
        Job.objects.filter(progress=x).update(progress=y)
    for x, y in PREF_CHOICES:
        Job.objects.filter(payment_preference=x).update(payment_preference=y)


def revert_fields(apps: Any, scheme_editor: Any):
    Job = apps.get_model('payments', 'job')
    for y, x in PROGRESS_CHOICES:
        Job.objects.filter(progress=x).update(progress=y)
    for y, x in PREF_CHOICES:
        Job.objects.filter(payment_preference=x).update(payment_preference=y)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_job_payment_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_preference',
            field=models.CharField(
                blank=True,
                choices=[('PREF_NONE', 'Not specified'), ('PREF_INVCRD', 'Invoice credits'),
                            ('PREF_PROBONO', 'Pro bono'), ('PREF_PAYPAL', 'PayPal'),
                            ('PREF_VENMO', 'Venmo'), ('PREF_ZELLE', 'Zelle')],
                default='',
                max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.CharField(
                choices=[('JOB_NEW', 'In progress'), ('JOB_REV', 'Revisions requested'),
                            ('JOB_SUB', 'Submitted'), ('JOB_VFD', 'Completed')],
                default='JOB_NEW',
                help_text='The current status of the job',
                max_length=8),
        ),
        migrations.RunPython(update_fields, revert_fields),
    ]
