# Generated by Django 4.0.8 on 2022-12-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_alter_job_spades_bounty_alter_job_usd_bounty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='due_date',
        ),
    ]
