# Generated by Django 4.1.4 on 2023-01-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0027_job_hours_estimate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="progress",
            field=models.CharField(
                choices=[
                    ("JOB_NEW", "Not submitted"),
                    ("JOB_REV", "Revisions requested"),
                    ("JOB_SUB", "Submitted"),
                    ("JOB_VFD", "Completed"),
                ],
                default="JOB_NEW",
                help_text="The current status of the job",
                max_length=8,
            ),
        ),
    ]
