# Generated by Django 4.1.4 on 2023-01-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0028_alter_job_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Evan can make internal notes here"
            ),
        ),
    ]
