# Generated by Django 4.1.5 on 2023-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0029_job_admin_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="name",
            field=models.CharField(help_text="Name of job", max_length=160),
        ),
    ]
