# Generated by Django 4.1.7 on 2023-03-20 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0030_alter_job_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="zelle_info",
            field=models.CharField(
                blank=True,
                help_text="Either email or mobile",
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(@[-a-zA-Z0-9_]+|(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)|^[0-9()+-]+)$"
                    )
                ],
            ),
        ),
    ]
