# Generated by Django 4.1.8 on 2023-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0031_alter_worker_zelle_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfolder",
            name="archived",
            field=models.BooleanField(
                default=False, help_text="Set to True when this folder is all done."
            ),
        ),
    ]
