# Generated by Django 4.1.10 on 2023-08-10 20:40

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_squashed_0032_jobfolder_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="description_rendered",
            field=markdownfield.models.RenderedMarkdownField(),
        ),
        migrations.AlterField(
            model_name="jobfolder",
            name="description_rendered",
            field=markdownfield.models.RenderedMarkdownField(),
        ),
        migrations.AlterField(
            model_name="jobfolder",
            name="slug",
            field=models.SlugField(help_text="A slug for this job folder"),
        ),
    ]
