# Generated by Django 4.2.4 on 2023-08-26 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0033_alter_job_created_at_alter_job_description_rendered_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="semester",
        ),
    ]
