# Generated by Django 5.2.6 on 2025-09-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0036_alter_paymentlog_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlog",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
    ]
