# Generated by Django 6.0.8 on 2026-08-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0037_paymentlog_refunded"),
        ("roster", "0118_applyuuid_applicant_name_applyuuid_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlog",
            name="refunded",
            field=models.BooleanField(
                default=False,
                help_text="Set when the payment has been fully refunded or charged back. Such rows are ignored when totaling up what a student has paid.",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("amount__gt", 0), models.Q(("stripe_id", ""), _negated=True)
                ),
                fields=("stripe_id",),
                name="unique_stripe_id_per_payment",
            ),
        ),
    ]
