# Generated by Django 4.2.7 on 2023-11-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_url", models.URLField(blank=True, help_text="URL for joining.")),
                (
                    "main_url",
                    models.URLField(help_text="Main URL for viewing the proposals."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TB_ACTIVE", "Active"),
                            ("TB_HIDDEN", "Hidden"),
                            ("TB_DONE", "Completed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("display_name", models.CharField(max_length=128)),
            ],
        ),
    ]
