# Generated by Django 4.2.7 on 2023-11-27 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tubes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tube",
                    models.ForeignKey(
                        help_text="The tube the user joined.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tubes.tube",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who joined.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tube")},
            },
        ),
    ]
