# Generated by Django 4.2.7 on 2023-11-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0002_joinrecord"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="joinrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="joinrecord",
            name="success",
            field=models.BooleanField(
                default=True, help_text="Set to False if things go wrong"
            ),
        ),
    ]
