# Generated by Django 4.2.7 on 2023-12-04 03:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0003_alter_joinrecord_unique_together_joinrecord_success"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joinrecord",
            old_name="created_at",
            new_name="activation_time",
        ),
    ]
