# Generated by Django 4.2.7 on 2023-12-04 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tubes", "0005_alter_joinrecord_activation_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joinrecord",
            name="success",
        ),
        migrations.RemoveField(
            model_name="tube",
            name="join_url",
        ),
        migrations.AddField(
            model_name="joinrecord",
            name="invite_url",
            field=models.URLField(blank=True, help_text="The URL for joining"),
        ),
        migrations.AlterField(
            model_name="joinrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who joined.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
