# Generated by Django 4.2.7 on 2023-12-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0007_tube_accepting_signups"),
    ]

    operations = [
        migrations.AddField(
            model_name="tube",
            name="description",
            field=models.TextField(
                blank=True, help_text="A short description what this is about."
            ),
        ),
    ]
