# Generated by Django 5.2.14 on 2026-06-14 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0008_tube_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OIMEContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Published name for all OIME testsolving interactions. Nicknames or usernames are fine if you prefer.",
                        max_length=200,
                    ),
                ),
                (
                    "casual_mode",
                    models.BooleanField(
                        default=False,
                        help_text="If set, this contributor browses casually: they can view every problem statement untimed and upvote, nothing is recorded, and they can no longer start timed sessions. Solutions stay hidden until revealed per-problem.",
                    ),
                ),
                (
                    "ranked_cutoff",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set each time this contributor returns to ranked mode from casual mode. Problems created at or before this time are no longer eligible for a timed solve by them (they could have browsed them casually) and stay browsable casually instead.",
                        null=True,
                    ),
                ),
                (
                    "hide_from_leaderboards",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, your name is shown as an anonymous alias on testsolving leaderboards.",
                    ),
                ),
                (
                    "hide_from_acknowledgments",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, your name is omitted of published testsolver acknowledgments in the final packet.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oime_contributor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OIMEProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit",
                    models.CharField(
                        blank=True,
                        help_text="How you'd like this problem credited (for example, to include coauthors). Defaults to your display name.",
                        max_length=200,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short title for the proposal. No spoilers!",
                        max_length=200,
                    ),
                ),
                (
                    "statement",
                    models.TextField(help_text="The problem statement, in LaTeX."),
                ),
                (
                    "answer",
                    models.IntegerField(
                        help_text="Integer answer (0-999).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "solution",
                    models.TextField(help_text="Full solution write-up, in LaTeX."),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("A", "Algebra"),
                            ("C", "Combinatorics"),
                            ("G", "Geometry"),
                            ("N", "Number Theory"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (1, "🔥 × 1 (AIME 1-3): 10 minutes"),
                            (2, "🔥 × 2 (AIME 4-6): 15 minutes"),
                            (3, "🔥 × 3 (AIME 7-9): 20 minutes"),
                            (4, "🔥 × 4 (AIME 10-12): 25 minutes"),
                            (5, "🔥 × 5 (AIME 13-15): 30 minutes"),
                        ],
                        help_text="Difficulty rating (affects testsolve time limits). CANNOT BE CHANGED AFTER SUBMISSION.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="Hide this problem from the active list (staff-visible only).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The contributor who wrote this problem.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="tubes.oimecontributor",
                    ),
                ),
                (
                    "upvotes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Contributors who have upvoted this problem after solving it.",
                        related_name="upvoted_proposals",
                        to="tubes.oimecontributor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="oimecontributor",
            name="revealed_proposals",
            field=models.ManyToManyField(
                blank=True,
                help_text="Proposals whose solution this contributor has chosen to reveal.",
                related_name="revealed_by",
                to="tubes.oimeproposal",
            ),
        ),
        migrations.CreateModel(
            name="OIMEComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tubes.oimecontributor",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tubes.oimeproposal",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OIMEFight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OIME_TBD", "In Progress"),
                            ("OIME_OK", "Solved"),
                            ("OIME_FAIL", "Gave Up"),
                            ("OIME_TLE", "Time Limit Exceeded"),
                            ("OIME_ALE", "Answer Limit Exceeded"),
                        ],
                        default="OIME_TBD",
                        max_length=15,
                    ),
                ),
                ("wrong_answers", models.PositiveSmallIntegerField(default=0)),
                (
                    "solve_time_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Only set when status is OIME_OK.",
                        null=True,
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fights",
                        to="tubes.oimecontributor",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fights",
                        to="tubes.oimeproposal",
                    ),
                ),
            ],
            options={
                "unique_together": {("contributor", "proposal")},
            },
        ),
    ]
