# Generated by Django 5.2.14 on 2026-06-17 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0009_oime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oimefight",
            name="solve_time_seconds",
        ),
    ]
