# Generated by Django 5.2.14 on 2026-06-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0009_oimeyear_oimecontributor_oimeproposal_oimecomment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oimeattempt",
            name="solve_time_seconds",
            field=models.IntegerField(
                blank=True, help_text="Only set when status is OIME_OK.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="oimeattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("OIME_TBD", "In Progress"),
                    ("OIME_OK", "Solved"),
                    ("OIME_FAIL", "Gave Up"),
                    ("OIME_TLE", "Time Limit Exceeded"),
                    ("OIME_ALE", "Answer Limit Exceeded"),
                ],
                default="OIME_TBD",
                max_length=15,
            ),
        ),
    ]
