# Generated by Django 6.0.8 on 2026-08-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0010_remove_solve_time_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="oimeproposal",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="Keep this problem as a private draft while you are still working on it. Drafts are hidden from everyone else and are only listed on your own drafts page; uncheck this box when it is ready for testsolving.",
                verbose_name="Draft",
            ),
        ),
    ]
