# Generated by Django 5.2.14 on 2026-06-08 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0010_oime_status_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oimeproposal",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "Tier I (AIME 1-3): 10 minutes"),
                    (2, "Tier II (AIME 4-6): 15 minutes"),
                    (3, "Tier III (AIME 7-9): 20 minutes"),
                    (4, "Tier IV (AIME 10-12): 25 minutes"),
                    (5, "Tier V (AIME 13-15): 30 minutes"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
