# Generated by Django 6.0.8 on 2026-08-11 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0011_oimeproposal_is_draft"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oimecomment",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="oimeproposal",
            options={"ordering": ("-created_at",)},
        ),
    ]
