# Generated by Django 5.2.14 on 2026-06-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0011_alter_oimeproposal_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="oimeproposal",
            name="title",
            field=models.CharField(
                default="", help_text="Short title for the proposal.", max_length=200
            ),
            preserve_default=False,
        ),
    ]
