# Generated by Django 5.2.14 on 2026-06-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0012_oime_proposal_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oimeattempt",
            name="year",
        ),
        migrations.AddField(
            model_name="oimecontributor",
            name="spoil_before",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, this contributor is spoiled on all proposals created before this time and cannot start new timed attempts on them.",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="OIMEParticipation",
        ),
        migrations.DeleteModel(
            name="OIMEYear",
        ),
    ]
