# Generated by Django 6.0.8 on 2026-08-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0012_alter_oimecomment_options_alter_oimeproposal_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oimeproposal",
            name="subject",
            field=models.CharField(
                choices=[("A", "Alg"), ("C", "Combo"), ("G", "Geo"), ("N", "NT")],
                max_length=1,
            ),
        ),
    ]
