# Generated by Django 5.2.14 on 2026-06-08 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0014_rename_oimeattempt_to_oimefight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oimefight",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fights",
                to="tubes.oimecontributor",
            ),
        ),
        migrations.AlterField(
            model_name="oimefight",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fights",
                to="tubes.oimeproposal",
            ),
        ),
    ]
