# Generated by Django 5.2.14 on 2026-06-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0016_casual_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="oimecontributor",
            name="ranked_cutoff",
            field=models.DateTimeField(
                blank=True,
                help_text="Set each time this contributor returns to ranked mode from casual mode. Problems created at or before this time are no longer eligible for a timed solve by them (they could have browsed them casually) and stay browsable casually instead.",
                null=True,
            ),
        ),
    ]
