# Generated by Django 5.2.14 on 2026-06-14 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0017_oimecontributor_ranked_cutoff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oimeproposal",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "🔥 × 1 (AIME 1-3): 10 minutes"),
                    (2, "🔥 × 2 (AIME 4-6): 15 minutes"),
                    (3, "🔥 × 3 (AIME 7-9): 20 minutes"),
                    (4, "🔥 × 4 (AIME 10-12): 25 minutes"),
                    (5, "🔥 × 5 (AIME 13-15): 30 minutes"),
                ],
                help_text="Difficulty rating (affects testsolve time limits). CANNOT BE CHANGED AFTER SUBMISSION.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="oimeproposal",
            name="title",
            field=models.CharField(
                help_text="Short title for the proposal. No spoilers!", max_length=200
            ),
        ),
    ]
