# Generated by Django 5.2.14 on 2026-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0018_alter_oimeproposal_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oimecontributor",
            name="hide_from_acknowledgments",
            field=models.BooleanField(
                default=False,
                help_text="If set, your name is left out of public testsolver acknowledgments.",
            ),
        ),
        migrations.AddField(
            model_name="oimecontributor",
            name="hide_from_leaderboards",
            field=models.BooleanField(
                default=False,
                help_text="If set, your name is shown as an anonymous alias on testsolving leaderboards.",
            ),
        ),
        migrations.AddField(
            model_name="oimeproposal",
            name="credit",
            field=models.CharField(
                blank=True,
                help_text="How you'd like this problem credited (for example, to include coauthors). Defaults to your display name.",
                max_length=200,
            ),
        ),
    ]
