# Generated by Django 5.2.14 on 2026-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tubes", "0019_oimecontributor_hide_from_acknowledgments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oimecontributor",
            name="display_name",
            field=models.CharField(
                help_text="Published name for all OIME testsolving interactions. Nicknames or usernames are fine if you prefer.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="oimecontributor",
            name="hide_from_acknowledgments",
            field=models.BooleanField(
                default=False,
                help_text="If checked, your name is omitted of published testsolver acknowledgments in the final packet.",
            ),
        ),
        migrations.AlterField(
            model_name="oimecontributor",
            name="hide_from_leaderboards",
            field=models.BooleanField(
                default=False,
                help_text="If checked, your name is shown as an anonymous alias on testsolving leaderboards.",
            ),
        ),
    ]
