# Generated by Django 3.2.8 on 2021-10-19 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0007_auto_20211019_1627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guess",
            name="value",
            field=models.FloatField(
                help_text="User's guess",
                validators=[django.core.validators.MinValueValidator(1e-06)],
            ),
        ),
    ]
