# Generated by Django 3.2.8 on 2021-10-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_alter_guess_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='weight',
            field=models.FloatField(default=4, help_text='The max score to assign to the market, used in the scoring function'),
        ),
    ]
