# Generated by Django 3.2.8 on 2021-11-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_market_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='answer',
            field=models.FloatField(
                blank=True, help_text='The answer to the question', null=True),
        ),
    ]
