# Generated by Django 3.2.9 on 2021-11-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0012_alter_guess_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="market",
            options={"ordering": ("-end_date",)},
        ),
    ]
