# Generated by Django 4.0.8 on 2022-11-15 15:41

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0017_alter_market_show_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='prompt_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='solution_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='market',
            name='prompt',
            field=markdownfield.models.MarkdownField(
                help_text='Full text of the question', rendered_field='prompt_rendered'),
        ),
        migrations.AlterField(
            model_name='market',
            name='solution',
            field=markdownfield.models.MarkdownField(
                blank=True,
                help_text='Comments that appear in the market results.',
                rendered_field='solution_rendered'),
        ),
    ]
