# Generated by Django 4.1.7 on 2023-03-27 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("markets", "0018_market_prompt_rendered_market_solution_rendered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this market",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
