# Generated by Django 5.1.5 on 2025-02-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0018_market_prompt_rendered_market_solution_rendered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="int_guesses_only",
            field=models.BooleanField(
                default=False, help_text="Only allow integer guesses for this market."
            ),
        ),
    ]
