# Generated by Django 6.0.8 on 2026-08-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0020_market_show_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="alpha",
            field=models.FloatField(
                blank=True,
                default=1,
                help_text="Exponent corresponding to harshness of the market, used in the scoring function; leave blank for special scoring.",
                null=True,
            ),
        ),
    ]
