# Generated by Django 5.2.6 on 2025-09-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0020_market_show_results'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='guess',
            name='is_latest',
            field=models.BooleanField(default=True, help_text='Whether this is the latest guess for this user and market.'),
        ),
    ]
