# Generated by Django 5.2.6 on 2025-09-28 22:56

from django.conf import settings
from django.db import migrations
from django.db.models import Count


def cleanup_duplicates(apps, schema_editor):
    Guess = apps.get_model('markets', 'Guess')
    
    duplicates = Guess.objects.values('user', 'market').annotate(count=Count('id')).filter(count__gt=1)
    print(f'Found {len(duplicates)} duplicate user-market pairs')
    
    for dup in duplicates:
        user_id = dup['user']
        market_id = dup['market']
        guesses = Guess.objects.filter(user_id=user_id, market_id=market_id).order_by('id')
        if guesses.count() > 1:
            to_keep = guesses.first()
            to_delete = guesses.exclude(id=to_keep.id)
            print(f'Deleting {to_delete.count()} duplicate guesses for user {user_id}, market {market_id}')
            to_delete.delete()


def reverse_cleanup_duplicates(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0021_alter_guess_unique_together_guess_is_latest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicates, reverse_cleanup_duplicates),
        migrations.AlterUniqueTogether(
            name="guess",
            unique_together={("user", "market")},
        ),
        migrations.RemoveField(
            model_name="guess",
            name="is_latest",
        ),
    ]
