# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_install_hook_types = [
  "pre-commit",
  "commit-msg",
  "pre-push"
]
default_stages = ["pre-commit"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-executables-have-shebangs" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "check-symlinks" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "detect-private-key" },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "mixed-line-ending" },
  {
    id = "trailing-whitespace",
    args = ["--markdown-linebreak-ext=md"]
  }
]

[[repos]]
repo = "meta"
hooks = [
  { id = "check-useless-excludes" },
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "ruff-format",
    name = "ruff format",
    entry = "uv run ruff format",
    language = "system",
    types = ["python"]
  },
  {
    id = "ruff-check",
    name = "ruff check",
    entry = "uv run ruff check",
    language = "system",
    args = ["--fix"],
    types = ["python"]
  },
  {
    id = "djlint-reformat",
    name = "djlint reformat",
    entry = "uv run djlint --reformat",
    language = "system",
    files = "templates/",
    types = ["html"]
  },
  {
    id = "djlint-check",
    name = "djlint check",
    entry = "uv run djlint",
    language = "system",
    files = "templates/",
    types = ["html"]
  },
  {
    id = "codespell",
    name = "codespell",
    entry = "uv run codespell",
    language = "system",
    types = ["text"]
  },
#  {
#    id = "ty",
#    name = "ty",
#    entry = "uv run ty check .",
#    language = "system",
#    types = ["python"]
#  }
]

[[repos]]
repo = "https://github.com/JoC0de/pre-commit-prettier"
rev = "v3.8.1"
hooks = [
  {
    id = "prettier",
    types_or = ["css", "javascript", "ts", "markdown", "json", "yaml"],
  }
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.10.10"
hooks = [
  { id = "uv-lock" }
]

[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.4.0"
hooks = [
  {
    id = "conventional-pre-commit",
    stages = ["commit-msg"],
    args = [
      "feat",
      "fix",
      "build",
      "ci",
      "chore",
      "docs",
      "drop",
      "edit",
      "perf",
      "polish",
      "root",
      "refactor",
      "revert",
      "style",
      "temp",
      "tests"
    ]
  }
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "make-fmt",
    name = "Format code",
    entry = "make fmt",
    language = "system",
    pass_filenames = false,
    stages = ["pre-push"],
    fail_fast= true
  },
  {
    id = "make-check",
    name = "Run Django checks",
    entry = "make check",
    language = "system",
    pass_filenames = false,
    stages = ["pre-push"],
    fail_fast= true
  },
  {
    id = "make-test",
    name = "Run tests",
    entry = "make test",
    language = "system",
    pass_filenames = false,
    stages = ["pre-push"],
    fail_fast= true
  }
]
