# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_unit_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="name",
            field=models.CharField(
                help_text="Text description such as 'Year III'",
                max_length=255,
                unique=True,
            ),
        ),
    ]
