# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-05 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20171205_0903"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="show_invoices",
            field=models.BooleanField(
                default=False,
                help_text="Whether to display invoices for this semester.",
            ),
        ),
    ]
