# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_semester_show_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="registration_open",
            field=models.BooleanField(
                default=False,
                help_text="Whether students can register for this semester yet.",
            ),
        ),
    ]
