# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-22 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20180531_1305"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unitgroup",
            options={"ordering": ("name",)},
        ),
    ]
