# Generated by Django 2.1.7 on 2019-08-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20190809_1211"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="calendar_url_meets_evan",
            field=models.TextField(
                blank=True,
                help_text="Link to calendar for students with meetings with Evan",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="calendar_url_no_meets_evan",
            field=models.TextField(
                blank=True,
                help_text="Link to calendar for students without meetings with Evan",
            ),
        ),
    ]
