# Generated by Django 3.0.7 on 2020-08-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20200314_1453"),
    ]

    operations = [
        migrations.RenameField(
            model_name="semester",
            old_name="facebook_url",
            new_name="social_url",
        ),
    ]
