# Generated by Django 3.0.7 on 2020-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auto_20200810_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="social_url",
            field=models.CharField(
                blank=True,
                help_text="The link to social platform for this year.",
                max_length=128,
            ),
        ),
    ]
