# Generated by Django 3.1.8 on 2021-04-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210427_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='classroom_url',
            field=models.CharField(blank=True, help_text='The entry point for the meeting room.', max_length=128),
        ),
    ]
