# Generated by Django 3.2.7 on 2021-09-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitgroup',
            name='hidden',
            field=models.BooleanField(
                default=False, help_text='Whether this unit is hidden from students'),
        ),
    ]
