# Generated by Django 3.2.7 on 2021-09-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_unitgroup_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='classroom_url',
        ),
    ]
