# Generated by Django 3.2.7 on 2021-09-14 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_unit_reveal_at_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="reveal_at_level",
        ),
    ]
