# Generated by Django 3.2.7 on 2021-09-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_unitgroup_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitgroup',
            name='subject',
            field=models.CharField(
                choices=[('A', 'Algebra (Hufflepuff)'), ('C', 'Combinatorics (Gryffindor)'),
                            ('G', 'Geometry (Slytherin)'), ('N', 'Number Theory (Ravenclaw)'),
                            ('F', 'Functional Equations'), ('M', 'Miscellaneous'),
                            ('K', 'Null')],
                help_text='The subject for the unit',
                max_length=2),
        ),
    ]
