# Generated by Django 3.2.7 on 2021-09-26 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_unitgroup_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time user was seen at all'),
            preserve_default=False,
        ),
    ]
