# Generated by Django 3.2.7 on 2021-09-26 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_announce_dismiss',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time user dismissed the emails modal.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_download_dismiss',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time user dismissed the downloads modal.'),
            preserve_default=False,
        ),
    ]
