# Generated by Django 4.0.7 on 2022-08-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_last_announce_dismiss_userprofile_last_email_dismiss'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public',
            field=models.BooleanField(default=False, help_text='Whether student name appears on public leaderboards, like the diamonds leaderboard.'),
        ),
    ]
