# Generated by Django 4.0.7 on 2022-08-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_userprofile_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='public',
        ),
    ]
