# Generated by Django 4.0.8 on 2022-12-02 17:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_calendar_urls_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitgroup',
            name='artwork',
            field=models.ImageField(blank=True, help_text='Artwork for this unit', null=True, upload_to=core.models.artwork_image_file_name),
        ),
    ]
