# Generated by Django 4.1.4 on 2022-12-30 18:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_unitgroup_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitgroup",
            name="artwork_thumb_md",
            field=models.ImageField(
                blank=True,
                help_text="Artwork for this unit",
                null=True,
                upload_to=core.models.artwork_thumb_md_file_name,
            ),
        ),
        migrations.AddField(
            model_name="unitgroup",
            name="artwork_thumb_sm",
            field=models.ImageField(
                blank=True,
                help_text="Artwork for this unit",
                null=True,
                upload_to=core.models.artwork_thumb_md_file_name,
            ),
        ),
    ]
