# Generated by Django 4.1.5 on 2023-01-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_unitgroup_artist_name_unitgroup_artist_show"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unitgroup",
            name="artist_show",
        ),
    ]
