# Generated by Django 4.1.5 on 2023-01-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_remove_unitgroup_artist_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="one_semester_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date after which invoices are only charged for one semester.",
                null=True,
            ),
        ),
    ]
