# Generated by Django 4.1.9 on 2023-07-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_semester_one_semester_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="calendar_url_meets_evan",
        ),
        migrations.AlterField(
            model_name="semester",
            name="calendar_url_no_meets_evan",
            field=models.URLField(
                blank=True, help_text="Link to calendar", max_length=1024
            ),
        ),
    ]
