# Generated by Django 4.1.9 on 2023-07-22 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_remove_semester_calendar_url_meets_evan_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="semester",
            old_name="calendar_url_no_meets_evan",
            new_name="calendar_url",
        ),
    ]
