# Generated by Django 4.1.10 on 2023-07-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_rename_calendar_url_no_meets_evan_semester_calendar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_artwork_on_curriculum",
            field=models.BooleanField(
                default=True,
                help_text="Show the artwork on the curriculum table",
                verbose_name="Show artwork",
            ),
        ),
    ]
