# Generated by Django 4.1.10 on 2023-08-07 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_remove_userprofile_last_download_dismiss"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="last_email_dismiss",
            new_name="last_notif_dismiss",
        ),
    ]
