# Generated by Django 4.1.10 on 2023-08-07 01:51

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_rename_last_email_dismiss_userprofile_last_notif_dismiss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_notif_dismiss",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                help_text="Last time user dismissed the notifications modal.",
            ),
        ),
    ]
