# Generated by Django 4.1.10 on 2023-08-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_userprofile_last_notif_dismiss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="new_progress",
            field=models.BooleanField(
                default=True,
                help_text="Level meters show progression towards the next value to level up rather than a fixed max value",
                verbose_name="New level meters progression",
            ),
        ),
    ]
