# Generated by Django 4.1.10 on 2023-08-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_userprofile_last_notif_dismiss"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="use_twemoji",
            field=models.BooleanField(
                default=False,
                help_text="Uses Twemoji for emojis instead of system emojis.",
                verbose_name="Use Twemoji",
            ),
        ),
    ]
