# Generated by Django 4.1.10 on 2023-08-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_userprofile_dynamic_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="use_twemoji",
            field=models.BooleanField(
                default=False,
                help_text="Uses Twemoji for emojis instead of system emojis.",
                verbose_name="Use Twemoji",
            ),
        ),
    ]
