# Generated by Django 4.1.10 on 2023-08-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_userprofile_new_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="new_progress",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dynamic_progress",
            field=models.BooleanField(
                default=True,
                help_text="Level meters show progression towards the next value to level up rather than a fixed max value",
                verbose_name="Dynamic level meters progression",
            ),
        ),
    ]
