# Generated by Django 4.1.10 on 2023-08-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_remove_userprofile_new_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dynamic_progress",
            field=models.BooleanField(
                default=False,
                help_text="Level meters show progression towards the next value to level up rather than a fixed max value",
                verbose_name="Dynamic level meters progression",
            ),
        ),
    ]
