# Generated by Django 4.1.10 on 2023-08-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_squashed_0054_userprofile_use_twemoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="end_year",
            field=models.IntegerField(help_text="The year in which OTIS will end"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="group",
            field=models.ForeignKey(
                help_text="The group that this unit belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.unitgroup",
            ),
        ),
    ]
