# Generated by Django 4.2.5 on 2023-10-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_userprofile_show_portal_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitgroup",
            name="guest",
            field=models.BooleanField(
                default=False, help_text="Whether this unit is a guest unit."
            ),
            preserve_default=False,
        ),
    ]
