# Generated by Django 4.2.5 on 2023-10-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_alter_unit_unique_together_unit_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="version",
            field=models.CharField(
                choices=[("V", "V (Secret)"), ("W", "W"), ("X", "X"), ("Y", "Y")],
                help_text="The version code for the handout, like W",
                max_length=2,
            ),
        ),
    ]
