# Generated by Django 4.2.5 on 2023-10-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_unitgroup_guest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unitgroup",
            name="guest",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_unit_petitions",
            field=models.BooleanField(
                default=True,
                help_text="Show previous unit petitions that you have requested. Useful to disable if you have far too many.",
                verbose_name="Show unit petitions",
            ),
        ),
    ]
