# Generated by Django 4.2.11 on 2024-04-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_remove_unitgroup_guest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitgroup",
            name="subject",
            field=models.CharField(
                choices=[
                    ("A", "Algebra (Hufflepuff)"),
                    ("C", "Combinatorics (Gryffindor)"),
                    ("G", "Geometry (Slytherin)"),
                    ("N", "Number Theory (Ravenclaw)"),
                    ("F", "Functional Equations"),
                    ("M", "Miscellaneous"),
                    ("K", "Secret"),
                    ("H", "Higher Math"),
                ],
                help_text="The subject for the unit",
                max_length=2,
            ),
        ),
    ]
