# Generated by Django 5.1.9 on 2025-05-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_alter_unitgroup_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="gradescope_key",
            field=models.CharField(
                blank=True,
                help_text="NO LONGER USED. Previously, the entry code for GradeScope this semester.",
                max_length=10,
            ),
        ),
    ]
