# Generated by Django 5.2.2 on 2025-07-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_alter_semester_gradescope_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_on_announcement",
            field=models.BooleanField(
                default=True,
                help_text="Receive all-student announcements. If this is set to False, announcements will only appear on OTIS-WEB",
                verbose_name="Receive emails for announcements",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_inquiry_complete",
            field=models.BooleanField(
                default=False,
                help_text="Receive an email when your petition has been processed.",
                verbose_name="Receive email on petition processed",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_pset_complete",
            field=models.BooleanField(
                default=True,
                help_text="Receive an email when your problem sets are checked off.",
                verbose_name="Receive email on completed problem set",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_registration_processed",
            field=models.BooleanField(
                default=False,
                help_text="Receive an email when your registration for the year is approved.",
                verbose_name="Receive email on registration",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_on_suggestion_processed",
            field=models.BooleanField(
                default=True,
                help_text="Receive an email when your problem suggestion status is updated.",
                verbose_name="Receive email on suggestion processed",
            ),
        ),
    ]
