# Generated by Django 5.2.4 on 2025-08-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_userprofile_email_on_announcement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dynamic_progress",
            field=models.BooleanField(
                default=False,
                help_text="Level meters show progression towards the next value to level up rather than a fixed max value.",
                verbose_name="Dynamic level meters progression",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_on_announcement",
            field=models.BooleanField(
                default=True,
                help_text="Receive all-student announcements. If this is set to False, announcements will only appear on OTIS-WEB.",
                verbose_name="Receive emails for announcements",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_artwork_on_curriculum",
            field=models.BooleanField(
                default=True,
                help_text="Show the artwork on the curriculum table.",
                verbose_name="Show artwork",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_bars",
            field=models.BooleanField(
                default=True,
                help_text="Displays the level bars on the main portal.",
                verbose_name="Level bars",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_completed_by_default",
            field=models.BooleanField(
                default=True,
                help_text="Displays completed units on the main portal by default.",
                verbose_name="Show completed",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_locked_by_default",
            field=models.BooleanField(
                default=True,
                help_text="Displays locked units on the main portal by default.",
                verbose_name="Show locked",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="show_portal_instructions",
            field=models.BooleanField(
                default=True,
                help_text="Show the instruction text above the units on the home page.",
                verbose_name="Show portal instructions",
            ),
        ),
    ]
