# Generated by Django 5.1.9 on 2025-08-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_userprofile_dynamic_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sort_units_by_subject',
            field=models.BooleanField(default=False, help_text='Automatically sort units by subject in the dashboard curriculum view.', verbose_name='Sort units by subject'),
        ),
    ]
