# Generated by Django 5.2.11 on 2026-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_alter_userprofile_dynamic_progress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="disable_hints",
            field=models.BooleanField(
                default=False,
                help_text="Hide all hints from the problem archive (ARCH).",
                verbose_name="Disable hints",
            ),
        ),
    ]
