# Generated by Django 5.2.6 on 2025-09-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_userprofile_dynamic_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sort_units_by_subject',
            field=models.BooleanField(default=False, help_text='Automatically sort curriculum units by subject in dashboard.', verbose_name='Auto-sort by subject'),
        ),
    ]
