# Generated by Django 5.2.7 on 2025-10-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_userprofile_dynamic_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_hint_mode',
            field=models.BooleanField(default=False, help_text='When enabled, blocks access to all hint-related features in ARCH.', verbose_name='No Hint Mode'),
        ),
    ]
