# Generated by Django 5.2.11 on 2026-03-01 22:05

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_userprofile_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your local time zone for displaying timestamps. Leave blank to use server time (America/New_York).",
                max_length=63,
                validators=[core.models.validate_timezone],
                verbose_name="Time zone",
            ),
        ),
    ]
