# Generated by Django 5.2.12 on 2026-03-05 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_userprofile_disable_hints"),
        ("core", "0065_alter_userprofile_timezone"),
    ]

    operations = []
