# Generated by Not Django 5.2.12 on 2026-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_userprofile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="inline_pdf",
            field=models.BooleanField(
                default=False,
                help_text="Open PDF files without downloading them permanently.",
                verbose_name="Display PDF inline",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="inline_tex",
            field=models.BooleanField(
                default=False,
                help_text="Open TeX files without downloading them permanently.",
                verbose_name="Display TeX inline",
            ),
        ),
    ]
