# Generated by Django 5.2.12 on 2026-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_userprofile_inline_pdf_userprofile_inline_tex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="inline_pdf",
            field=models.BooleanField(
                default=True,
                help_text="Uses inline content-disposition for PDF instead of attachment. May not be supported in all browsers.",
                verbose_name="Open PDF files inline",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="inline_tex",
            field=models.BooleanField(
                default=True,
                help_text="Uses inline content-disposition for TeX instead of attachment. May not be supported in all browsers.",
                verbose_name="Open TeX files inline",
            ),
        ),
    ]
