# Generated by Django 5.2.14 on 2026-06-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_alter_userprofile_inline_pdf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unitgroup",
            name="artwork",
        ),
        migrations.RemoveField(
            model_name="unitgroup",
            name="artwork_thumb_md",
        ),
        migrations.RemoveField(
            model_name="unitgroup",
            name="artwork_thumb_sm",
        ),
        migrations.AlterField(
            model_name="unitgroup",
            name="artist_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the artist for the unit artwork. A nonempty value marks the artwork as finished and available on the CDN.",
                max_length=64,
            ),
        ),
    ]
