# Generated by Django 5.2.16 on 2026-08-02 01:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_remove_unitgroup_artwork_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email_on_registration_processed",
        ),
    ]
