# Generated by Django 5.2.16 on 2026-08-02 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_remove_userprofile_email_on_registration_processed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="gradescope_key",
        ),
    ]
