# Generated by Django 6.0.8 on 2026-08-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_remove_semester_gradescope_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="first_payment_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for half payment.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="most_payment_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for full payment.", null=True
            ),
        ),
    ]
