# Generated by Django 6.0.8 on 2026-08-25 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0072_rename_first_payment_deadline_semester_half_payment_deadline_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="email_on_inquiry_complete",
            new_name="email_on_petition_complete",
        ),
    ]
