# Generated by Django 6.0.8 on 2026-09-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_rename_userprofile_email_on_petition_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_color",
            field=models.CharField(
                choices=[
                    ("teal", "Teal (default)"),
                    ("pink", "Pink"),
                    ("green", "Green"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("blue", "Blue"),
                    ("indigo", "Indigo"),
                    ("purple", "Purple"),
                ],
                default="teal",
                help_text="Color scheme for the site background.",
                max_length=15,
                verbose_name="Display color",
            ),
        ),
    ]
