# Generated by Django 4.0.8 on 2022-11-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsuggestion",
            name="hyperlink",
            field=models.URLField(
                blank=True, help_text="A hyperlink if appropriate, e.g. AoPS thread."
            ),
        ),
    ]
