# Generated by Django 4.0.8 on 2022-12-15 01:00

from typing import Any

from django.db import migrations, models


def set_status(apps: Any, scheme_editor: Any):
    ProblemSuggestion = apps.get_model("suggestions", "ProblemSuggestion")
    ProblemSuggestion.objects.filter(resolved=True).update(status="SUGG_OK")


def unset_status(apps: Any, scheme_editor: Any):
    ProblemSuggestion = apps.get_model("suggestions", "ProblemSuggestion")
    ProblemSuggestion.objects.filter(status__in=("SUGG_NEW", "SUGG_EDIT")).update(
        resolved=False
    )
    ProblemSuggestion.objects.filter(
        status__in=("SUGG_NOK", "SUGG_OK", "SUGG_REJ")
    ).update(resolved=False)


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0002_problemsuggestion_hyperlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsuggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUGG_EDIT", "Edits requested"),
                    ("SUGG_NEW", "Pending"),
                    ("SUGG_NOK", "Nice rejection"),
                    ("SUGG_OK", "Accepted"),
                    ("SUGG_REJ", "Rejected"),
                ],
                default="SUGG_NEW",
                help_text="The current status of the suggestion",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            set_status,
            unset_status,
        ),
        migrations.RemoveField(
            model_name="problemsuggestion",
            name="resolved",
        ),
    ]
