# Generated by Django 4.0.8 on 2022-12-30 01:20

from django.db import migrations, models
from django.db.models import F


def set_updated_at(apps, schema_editor):
    ProblemSuggestion = apps.get_model("suggestions", "ProblemSuggestion")
    ProblemSuggestion.objects.update(updated_at=F("created_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0004_alter_problemsuggestion_hyperlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsuggestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(set_updated_at, migrations.RunPython.noop),
    ]
