# Generated by Django 4.1.7 on 2023-03-07 23:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0006_problemsuggestion_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problemsuggestion",
            old_name="feedback",
            new_name="staff_comments",
        ),
    ]
