# Generated by Django 5.0.7 on 2024-07-28 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0007_rename_feedback_problemsuggestion_staff_comments"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="problemsuggestion",
            table=None,
        ),
    ]
