# Generated by Django 5.0.7 on 2024-07-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0009_alter_problemsuggestion_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemsuggestion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
