# Generated by Django 6.0.8 on 2026-09-23 15:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0073_rename_userprofile_email_on_petition_complete"),
        ("roster", "0124_alter_invoice_forgive_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PonziScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("start_date", models.DateTimeField(help_text="When investments open")),
                (
                    "collapsed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When somebody tried to withdraw more than the pool held",
                        null=True,
                    ),
                ),
                (
                    "collapsed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The student whose withdrawal broke the bank",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="roster.student",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.semester"
                    ),
                ),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="PonziInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        help_text="Number of spades invested, at most 10",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "target_tier",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The tier this investment reaches once its current timer runs out",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "upgraded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the most recent upgrade timer started",
                        null=True,
                    ),
                ),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roster.student"
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to="ponzi.ponzischeme",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
