# Generated by Django 4.1.10 on 2023-08-10 20:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import dashboard.models
import rpg.models


class Migration(migrations.Migration):
    replaces = [
        ("dashboard", "0001_initial"),
        ("dashboard", "0002_auto_20170810_2207"),
        ("dashboard", "0003_auto_20170810_2209"),
        ("dashboard", "0004_auto_20170813_1040"),
        ("dashboard", "0005_uploadedfile_created_at"),
        ("dashboard", "0006_auto_20170813_1057"),
        ("dashboard", "0007_auto_20170813_1138"),
        ("dashboard", "0008_auto_20170814_2138"),
        ("dashboard", "0009_auto_20170818_1605"),
        ("dashboard", "0010_uploadedfile_description"),
        ("dashboard", "0011_auto_20181206_1148"),
        ("dashboard", "0012_auto_20190327_1911"),
        ("dashboard", "0013_auto_20190817_2254"),
        ("dashboard", "0014_semesterdownloadfile"),
        ("dashboard", "0015_problemsuggestion"),
        ("dashboard", "0016_problemsuggestion_created_at"),
        ("dashboard", "0017_auto_20210130_1306"),
        ("dashboard", "0018_problemsuggestion_acknowledge"),
        ("dashboard", "0019_auto_20210130_2059"),
        ("dashboard", "0020_problemsuggestion_notified"),
        ("dashboard", "0021_psetsubmission"),
        ("dashboard", "0022_auto_20210730_1953"),
        ("dashboard", "0023_auto_20210802_1917"),
        ("dashboard", "0024_achievementcode_level"),
        ("dashboard", "0025_auto_20210802_2344"),
        ("dashboard", "0026_rename_number_level_threshold"),
        ("dashboard", "0027_rename_psetsubmission_pset"),
        ("dashboard", "0028_alter_pset_next_unit_to_unlock"),
        ("dashboard", "0029_auto_20210804_1857"),
        ("dashboard", "0030_rename_achievementcode_achievement"),
        ("dashboard", "0031_achievement_name"),
        ("dashboard", "0032_alter_achievement_active"),
        ("dashboard", "0033_auto_20210804_2035"),
        ("dashboard", "0034_auto_20210815_0147"),
        ("dashboard", "0035_remove_problemsuggestion_notified"),
        ("dashboard", "0036_achievementunlock"),
        ("dashboard", "0037_auto_20210818_1836"),
        ("dashboard", "0038_alter_pset_upload"),
        ("dashboard", "0039_alter_achievement_diamonds"),
        ("dashboard", "0040_auto_20210820_0034"),
        ("dashboard", "0041_remove_pset_instructor_comments"),
        ("dashboard", "0042_questcomplete"),
        ("dashboard", "0043_alter_achievementunlock_unique_together"),
        ("dashboard", "0044_alter_level_name"),
        ("dashboard", "0045_remove_problemsuggestion_reason"),
        ("dashboard", "0046_auto_20210912_1122"),
        ("dashboard", "0047_bonuslevel_bonuslevelunlock"),
        ("dashboard", "0048_auto_20210916_2053"),
        ("dashboard", "0049_auto_20210916_2058"),
        ("dashboard", "0050_auto_20210916_2110"),
        ("dashboard", "0051_alter_palaceentry_image"),
        ("dashboard", "0052_auto_20210916_2115"),
        ("dashboard", "0053_auto_20210916_2210"),
        ("dashboard", "0054_alter_palaceentry_student"),
        ("dashboard", "0055_rename_palaceentry_palacecarving"),
        ("dashboard", "0056_auto_20210917_1213"),
        ("dashboard", "0057_alter_achievement_code"),
        ("dashboard", "0058_alter_semesterdownloadfile_content"),
        ("dashboard", "0059_problemsuggestion_user"),
        ("dashboard", "0060_auto_20211017_1800"),
        ("dashboard", "0061_alter_problemsuggestion_user"),
        ("dashboard", "0062_auto_20211017_1819"),
        ("dashboard", "0063_alter_pset_next_unit_to_unlock"),
        ("dashboard", "0064_questcomplete_category"),
        ("dashboard", "0065_alter_questcomplete_category"),
        ("dashboard", "0066_problemsuggestion_eligible"),
        ("dashboard", "0067_alter_achievement_code"),
        ("dashboard", "0068_alter_achievement_code"),
        ("dashboard", "0069_alter_pset_options"),
        ("dashboard", "0070_auto_20220124_1249"),
        ("dashboard", "0071_pset_rejected"),
        ("dashboard", "0072_achievement_solution"),
        ("dashboard", "0073_achievement_always_show_image_alter_achievement_code"),
        ("dashboard", "0074_alter_uploadedfile_content"),
        ("dashboard", "0075_alter_achievement_always_show_image_and_more"),
        ("dashboard", "0076_alter_pset_upload"),
        ("dashboard", "0077_pset_status"),
        ("dashboard", "0078_auto_20220926_1303"),
        ("dashboard", "0079_remove_pset_approved_remove_pset_rejected_and_more"),
        ("dashboard", "0080_alter_pset_clubs_alter_pset_hours"),
        ("dashboard", "0081_delete_problemsuggestion"),
        ("dashboard", "0082_remove_achievement_creator_and_more"),
        ("dashboard", "0083_pset_comments"),
        ("dashboard", "0084_rename_comments_pset_staff_comments"),
        ("dashboard", "0085_alter_pset_staff_comments"),
    ]

    initial = True

    dependencies = [
        ("core", "0024_alter_unitgroup_slug"),
        ("core", "0005_unit_subject"),
        ("core", "0015_auto_20200314_1453"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0033_remove_unit_reveal_at_level"),
        ("roster", "0061_alter_registrationcontainer_allowed_tracks"),
        ("roster", "0062_student_achievements"),
        ("roster", "0075_remove_student_last_level_time"),
        ("core", "0027_alter_semester_uses_legacy_pset_system"),
        ("core", "0018_auto_20200908_1307"),
        ("roster", "0009_auto_20170808_1730"),
        ("roster", "0049_auto_20210111_1623"),
        ("core", "0037_rename_last_announce_dismiss_userprofile_last_email_dismiss"),
        ("roster", "0071_remove_student_usemo_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("psets", "PSet Submission"),
                            ("scripts", "Transcript"),
                            ("notes", "Notes / Comments"),
                            ("misc", "Miscellaneous"),
                        ],
                        help_text="What kind of file this is",
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        help_text="Upload your write-ups as PDF, TeX, TXT, PNG, or JPG. At most one file.",
                        upload_to=dashboard.models.content_file_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "txt", "tex", "png", "jpg"]
                            )
                        ],
                        verbose_name="Your submission",
                    ),
                ),
                (
                    "benefactor",
                    models.ForeignKey(
                        help_text="The student for which this file is meant",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roster.student",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="The unit for which this file is associated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.unit",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of the file",
                        max_length=250,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=96,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="24-26 char hex string",
                                regex="^[a-f0-9]{24,26}$",
                            )
                        ],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for the obtained achievement, at most 1MB.",
                        null=True,
                        upload_to=rpg.models.achievement_image_file_name,
                        validators=[dashboard.models.validate_at_most_1mb],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Text shown beneath this achievement for students who obtain it.",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether the code is active right now"
                    ),
                ),
                (
                    "diamonds",
                    models.SmallIntegerField(
                        default=0, help_text="Number of diamonds for this achievement"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", help_text="Name of the achievement", max_length=128
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this achievement",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True,
                        help_text="Description of where the diamond is hidden",
                    ),
                ),
                (
                    "always_show_image",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, always show the achievement image, even if no one earned the diamond yet.",
                        verbose_name="Reveal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold",
                    models.IntegerField(
                        help_text="The number of the level", unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The name of the level", max_length=128),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BonusLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(help_text="Level to spawn at"),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.unitgroup"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BonusLevelUnlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "bonus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.bonuslevel",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roster.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SemesterDownloadFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of the file",
                        max_length=250,
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        help_text="The file itself",
                        upload_to=dashboard.models.download_file_name,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="The semester to which the file is associated",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.semester",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="QuestComplete",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="A summary", max_length=160)),
                (
                    "spades",
                    models.PositiveSmallIntegerField(
                        help_text="The number of spades granted"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the achievement was granted",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student obtaining this reward",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roster.student",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PR", "Pull request"),
                            ("BR", "Bug report"),
                            ("WK", "Wiki bonus"),
                            ("US", "USEMO Score"),
                            ("UG", "USEMO Grading"),
                            ("MS", "Miscellaneous"),
                        ],
                        default="MS",
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemSuggestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(2, 2), (3, 3), (5, 5), (9, 9)], null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of the problem, e.g. `Shortlist 2018 A7`.",
                        max_length=60,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A one-line summary of problem, e.g. `Inequality with cube roots`.",
                        max_length=100,
                    ),
                ),
                (
                    "statement",
                    models.TextField(help_text="Statement of the problem, in LaTeX."),
                ),
                (
                    "solution",
                    models.TextField(help_text="Solution to the problem, in LaTeX."),
                ),
                (
                    "comments",
                    models.TextField(blank=True, help_text="Any extra comments."),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Whether staff has processed this."
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="The unit to suggest the problem for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.unit",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "acknowledge",
                    models.BooleanField(
                        default=True,
                        help_text="Acknowledge me for this contribution. (Uncheck for an anonymous contribution.)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who suggested the problem.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eligible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this suggestion is eligible for spades.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PalaceCarving",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="How you would like your name to be displayed in the Ruby Palace.",
                        max_length=128,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="You can write a message here",
                        max_length=1024,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visible",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide your carving altogether (can change your mind later)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional small photo that will appear next to your carving, no more than 1 megabyte",
                        null=True,
                        upload_to=rpg.models.palace_image_file_name,
                        validators=[dashboard.models.validate_at_most_1mb],
                    ),
                ),
                (
                    "hyperlink",
                    models.URLField(
                        blank=True, help_text="An external link of your choice"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AchievementUnlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the achievement was granted",
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        help_text="The achievement that was obtained",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who unlocked the achievement",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="PSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.FloatField(
                        blank=True,
                        help_text="Number of hours (♥) spent on this problem set",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="♥ Hours spent (estimate)",
                    ),
                ),
                (
                    "clubs",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of clubs (♣) that you solved, including 1♣ for feedback",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="♣ Clubs earned",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Any other feedback about the problem set",
                        verbose_name="Feedback on problem set, worth [1♣]",
                    ),
                ),
                (
                    "special_notes",
                    models.TextField(
                        blank=True,
                        help_text="If there's anything you need to say before we proceed",
                    ),
                ),
                (
                    "next_unit_to_unlock",
                    models.ForeignKey(
                        blank=True,
                        help_text="The unit you want to work on next (leave blank for none)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unblocking_psets",
                        to="core.unit",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student attached to this",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roster.student",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="The unit you want to submit for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.unit",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        help_text="The associated upload file for this problem set",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.uploadedfile",
                    ),
                ),
                (
                    "eligible",
                    models.BooleanField(
                        default=True, help_text="Whether to count this for leveling up"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Accepted"),
                            ("R", "Rejected"),
                            ("PA", "Pending (prev accepted)"),
                            ("PR", "Pending (prev rejected)"),
                            ("P", "Pending (new)"),
                        ],
                        default="P",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "verbose_name": "PSet submission",
                "verbose_name_plural": "PSet submissions",
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="ProblemSuggestion",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="achievement",
                    name="creator",
                ),
                migrations.AlterUniqueTogether(
                    name="achievementunlock",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="achievementunlock",
                    name="achievement",
                ),
                migrations.RemoveField(
                    model_name="achievementunlock",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="bonuslevel",
                    name="group",
                ),
                migrations.RemoveField(
                    model_name="bonuslevelunlock",
                    name="bonus",
                ),
                migrations.RemoveField(
                    model_name="bonuslevelunlock",
                    name="student",
                ),
                migrations.DeleteModel(
                    name="Level",
                ),
                migrations.RemoveField(
                    model_name="palacecarving",
                    name="user",
                ),
                migrations.RemoveField(
                    model_name="questcomplete",
                    name="student",
                ),
                migrations.DeleteModel(
                    name="Achievement",
                ),
                migrations.DeleteModel(
                    name="AchievementUnlock",
                ),
                migrations.DeleteModel(
                    name="BonusLevel",
                ),
                migrations.DeleteModel(
                    name="BonusLevelUnlock",
                ),
                migrations.DeleteModel(
                    name="PalaceCarving",
                ),
                migrations.DeleteModel(
                    name="QuestComplete",
                ),
            ],
        ),
        migrations.AddField(
            model_name="pset",
            name="staff_comments",
            field=models.TextField(
                blank=True, help_text="Comments by Evan on this problem set"
            ),
        ),
    ]
