# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_auto_20170810_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="description",
            field=models.CharField(
                blank=True, help_text="A description of the file", max_length=160
            ),
        ),
    ]
