# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_auto_20170813_1057"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="file_type",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="file_content",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="uploadedfile",
            name="description",
        ),
    ]
