# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_auto_20170813_1138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="content",
            field=models.FileField(help_text="The file itself", upload_to=""),
        ),
    ]
