# Generated by Django 3.0.7 on 2021-01-30 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_problemsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsuggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
