# Generated by Django 3.0.7 on 2021-01-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_problemsuggestion_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problemsuggestion",
            old_name="reviewed",
            new_name="resolved",
        ),
    ]
