# Generated by Django 3.0.7 on 2021-01-31 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_problemsuggestion_acknowledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemsuggestion',
            old_name='review_notes',
            new_name='reason',
        ),
    ]
