# Generated by Django 3.2.5 on 2021-07-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_psetsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="psetsubmission",
            name="feedback",
            field=models.TextField(
                blank=True,
                help_text="Any other feedback about the problem set",
                verbose_name="Feedback on problem set, worth [1♣]",
            ),
        ),
        migrations.AlterField(
            model_name="psetsubmission",
            name="special_notes",
            field=models.TextField(
                blank=True,
                help_text="If there's anything you need to say before we proceed",
            ),
        ),
    ]
