# Generated by Django 3.2.5 on 2021-08-04 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0025_auto_20210802_2344"),
    ]

    operations = [
        migrations.RenameField(
            model_name="level",
            old_name="number",
            new_name="threshold",
        ),
    ]
