# Generated by Django 3.2.5 on 2021-08-04 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0061_alter_registrationcontainer_allowed_tracks"),
        ("core", "0027_alter_semester_uses_legacy_pset_system"),
        ("dashboard", "0026_rename_number_level_threshold"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PSetSubmission",
            new_name="PSet",
        ),
    ]
