# Generated by Django 3.2.5 on 2021-08-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_achievement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='active',
            field=models.BooleanField(
                default=True, help_text='Whether the code is active right now'),
        ),
    ]
