# Generated by Django 3.2.6 on 2021-08-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_auto_20210815_0147"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problemsuggestion",
            name="notified",
        ),
    ]
