# Generated by Django 3.2.6 on 2021-08-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0037_auto_20210818_1836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pset",
            name="upload",
            field=models.ForeignKey(
                help_text="The associated upload file for this problem set",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.uploadedfile",
            ),
        ),
    ]
