# Generated by Django 3.2.6 on 2021-08-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_pset_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='diamonds',
            field=models.SmallIntegerField(default=1, help_text='Amount of diamonds for this achievement'),
        ),
    ]
