# Generated by Django 3.2.6 on 2021-08-28 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0040_auto_20210820_0034"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pset",
            name="instructor_comments",
        ),
    ]
