# Generated by Django 3.2.6 on 2021-08-29 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0042_questcomplete"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="achievementunlock",
            unique_together={("user", "achievement")},
        ),
    ]
