# Generated by Django 3.2.6 on 2021-08-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_achievementunlock_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(help_text='The name of the level', max_length=128),
        ),
    ]
