# Generated by Django 3.2.7 on 2021-09-14 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0075_remove_student_last_level_time"),
        ("core", "0033_remove_unit_reveal_at_level"),
        ("dashboard", "0046_auto_20210912_1122"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(help_text="Level to spawn at"),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.unitgroup"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BonusLevelUnlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "bonus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.bonuslevel",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roster.student"
                    ),
                ),
            ],
        ),
    ]
