# Generated by Django 3.2.7 on 2021-09-17 01:10

from django.db import migrations, models

import dashboard.models
import rpg.models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0049_auto_20210916_2058"),
    ]

    operations = [
        migrations.AddField(
            model_name="palaceentry",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional small photo of yourself you want to use",
                null=True,
                upload_to=rpg.models.achievement_image_file_name,
                validators=[dashboard.models.validate_at_most_1mb],
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image for the obtained badge",
                null=True,
                upload_to=rpg.models.achievement_image_file_name,
                validators=[dashboard.models.validate_at_most_1mb],
            ),
        ),
        migrations.AlterField(
            model_name="palaceentry",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide your entry altogether (can change your mind later)",
            ),
        ),
    ]
