# Generated by Django 3.2.7 on 2021-09-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0075_remove_student_last_level_time"),
        ("dashboard", "0054_alter_palaceentry_student"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PalaceEntry",
            new_name="PalaceCarving",
        ),
    ]
