# Generated by Django 3.2.8 on 2021-10-17 22:00

from django.db import migrations


def refactor_suggestion(apps, schema_editor):
	suggestions = apps.get_model('dashboard', 'ProblemSuggestion')
	for s in suggestions.objects.all().select_related('student__user'):
		s.user = s.student.user
		s.save()


class Migration(migrations.Migration):
	dependencies = [
		('dashboard', '0059_problemsuggestion_user'),
	]
	operations = [migrations.RunPython(refactor_suggestion, migrations.RunPython.noop)]
