# Generated by Django 3.2.8 on 2021-10-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_questcomplete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questcomplete',
            name='category',
            field=models.CharField(
                choices=[('PR', 'Pull request'), ('BR', 'Bug report'), ('WK', 'Wiki bonus'),
                            ('US', 'USEMO Score'), ('UG', 'USEMO Grading'),
                            ('MS', 'Miscellaneous')],
                default='MS',
                max_length=4),
        ),
    ]
