# Generated by Django 4.0.5 on 2022-09-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0075_alter_achievement_always_show_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pset",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                help_text="The associated upload file for this problem set",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.uploadedfile",
            ),
        ),
    ]
