# Generated by Django 4.0.7 on 2022-09-27 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_remove_pset_approved_remove_pset_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pset',
            name='clubs',
            field=models.IntegerField(blank=True, help_text='Total number of clubs (♣) that you solved, including 1♣ for feedback', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='♣ Clubs earned'),
        ),
        migrations.AlterField(
            model_name='pset',
            name='hours',
            field=models.FloatField(blank=True, help_text='Number of hours (♥) spent on this problem set', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='♥ Hours spent (estimate)'),
        ),
    ]
