# Generated by Django 4.1.7 on 2023-03-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0082_remove_achievement_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pset",
            name="comments",
            field=models.TextField(
                blank=True, help_text="Comments by Evan on this Unit Set"
            ),
        ),
    ]
