# Generated by Django 4.1.7 on 2023-03-07 23:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0083_pset_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pset",
            old_name="comments",
            new_name="staff_comments",
        ),
    ]
