# Generated by Django 4.1.10 on 2023-08-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_squashed_0085_alter_pset_staff_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
