# Generated by Django 4.2.5 on 2023-09-12 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0103_alter_assistant_user_alter_invoice_created_at_and_more"),
        ("core", "0057_userprofile_show_portal_instructions"),
        ("dashboard", "0086_alter_uploadedfile_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pset",
            unique_together={("student", "unit")},
        ),
    ]
