# Generated by Django 5.1.4 on 2024-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0087_alter_pset_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pset",
            name="feedback",
            field=models.TextField(
                blank=True,
                help_text="Any feedback about the unit",
                verbose_name="Feedback on unit, worth [1♣]",
            ),
        ),
    ]
