# Generated by Django 5.2.2 on 2025-08-01 13:19

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0088_alter_pset_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject line for announcement", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug for the announcement URL", unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    markdownfield.models.MarkdownField(
                        help_text="Content of the announcement",
                        rendered_field="content_rendered",
                    ),
                ),
                ("content_rendered", markdownfield.models.RenderedMarkdownField()),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
