# Generated by Django 5.2.6 on 2025-09-16 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0089_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pset",
            name="upload",
            field=models.OneToOneField(
                blank=True,
                help_text="The associated upload file for this problem set",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.uploadedfile",
            ),
        ),
    ]
