# Generated by Django 6.0.7 on 2026-08-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0090_alter_pset_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Announcements from past years, de-emphasized in the listing",
            ),
        ),
    ]
