# Generated by Django 6.0.8 on 2026-08-24 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0091_announcement_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pset",
            name="clubs",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of clubs (♣) that you solved, including 1♣ for feedback. Do not apply the ×1.3 or ×1.5 bonus for D and Z units.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="♣ Clubs earned",
            ),
        ),
    ]
