# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_assignment_due_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mockolympiad',
            unique_together={('family', 'number')},
        ),
    ]
