# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_auto_20170808_1707"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="olympiad",
        ),
        migrations.AddField(
            model_name="mockolympiad",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="When the assignment should be due. Leave blank if not active this semester.",
                null=True,
            ),
        ),
    ]
