# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_unit_subject'),
        ('exams', '0004_auto_20170810_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(help_text='Name / description of the assignment', max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([('semester', 'name')]),
        ),
    ]
