# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20170818_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockolympiad',
            name='start_date',
            field=models.DateField(blank=True, help_text='When the assignment opens. Leave blank if not active this semester.', null=True),
        ),
    ]
