# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0013_auto_20180531_1333"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practiceexam",
            options={"ordering": ("family", "-is_test", "number")},
        ),
    ]
