# Generated by Django 3.2.5 on 2021-08-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0061_alter_registrationcontainer_allowed_tracks'),
        ('exams', '0015_examsubmission_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamSubmission',
            new_name='ExamAttempt',
        ),
    ]
