# Generated by Django 3.2.5 on 2021-08-05 18:01

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0019_auto_20210805_1334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="guess1",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1000000000),
                    django.core.validators.MaxValueValidator(1000000000),
                ],
                verbose_name="Problem 1 response",
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="guess2",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1000000000),
                    django.core.validators.MaxValueValidator(1000000000),
                ],
                verbose_name="Problem 2 response",
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="guess3",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1000000000),
                    django.core.validators.MaxValueValidator(1000000000),
                ],
                verbose_name="Problem 3 response",
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="guess4",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1000000000),
                    django.core.validators.MaxValueValidator(1000000000),
                ],
                verbose_name="Problem 4 response",
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="guess5",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1000000000),
                    django.core.validators.MaxValueValidator(1000000000),
                ],
                verbose_name="Problem 5 response",
            ),
        ),
        migrations.AlterField(
            model_name="practiceexam",
            name="answer1",
            field=models.CharField(
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="practiceexam",
            name="answer2",
            field=models.CharField(
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="practiceexam",
            name="answer3",
            field=models.CharField(
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="practiceexam",
            name="answer4",
            field=models.CharField(
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="practiceexam",
            name="answer5",
            field=models.CharField(
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
