# Generated by Django 3.2.5 on 2021-08-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0021_auto_20210805_1404"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="score",
            field=models.SmallIntegerField(
                blank=True, help_text="The number of correct answers", null=True
            ),
        ),
    ]
