# Generated by Django 3.2.8 on 2021-10-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0029_auto_20211022_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mockcompleted',
            options={'verbose_name_plural': 'Mock completions'},
        ),
    ]
