# Generated by Django 5.0.7 on 2024-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_squashed_0033_mockcompleted_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockcompleted",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
