# Generated by Django 3.0.7 on 2021-01-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arch", "0002_auto_20210121_2112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hint",
            name="keywords",
            field=models.CharField(
                default="",
                help_text="A comma-separated list of keywords that a solver could look at to help them guess whether the hint is relevant or not. These are viewable immediately, so no spoilers here.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="number",
            field=models.PositiveIntegerField(
                help_text="A number from 0 to 100 used to indicate an ordering for the hints. Here a number 0 means a small nudge given to someone at the very start whereas 100 means a hint given to someone who was read all previous hints or is close to the end of the problem. Do your best to make up an extrapolation for everything in between. A good idea is to give a sequence of hints with nearby numbers, say 20/21/22, each of which elaborates on the previous hint."
            ),
        ),
    ]
