# Generated by Django 3.0.7 on 2021-01-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arch", "0005_auto_20210122_0008"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hint",
            options={},
        ),
    ]
