# Generated by Django 3.0.7 on 2021-01-22 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arch", "0006_auto_20210122_0021"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={},
        ),
    ]
