# Generated by Django 3.0.7 on 2021-02-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch", "0009_auto_20210122_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hint",
            name="keywords",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A comma-separated list of keywords that a solver could look at to help them guess whether the hint is relevant or not. These are viewable immediately, so no spoilers here. Examples are `answer confirmation`, `nudge`, `main idea`, `solution set`,`converse direction`, `construction`, etc. Not all hints go well with keywords, so you can leave this blank if you can't think of anything useful to write.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="number",
            field=models.PositiveIntegerField(
                help_text="A number from 0 to 100 used to indicate an ordering for the hints. Here a number 0 means a hint given to someone at the very start whereas 100 means a hint given to someone who was read all previous hints or is close to the end of the problem. Do your best to make up an extrapolation for everything in between. A good idea is to give a sequence of hints with nearby numbers, say 20/21/22, each of which elaborates on the previous hint."
            ),
        ),
    ]
