# Generated by Django 3.1.8 on 2021-06-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch", "0016_auto_20210604_0915"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="puid",
            field=models.CharField(
                help_text="Unique problem identifier, as printed in OTIS handout.",
                max_length=24,
                unique=True,
            ),
        ),
    ]
