# Generated by Django 3.2.6 on 2021-08-20 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arch", "0018_auto_20210815_1731"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ("puid",)},
        ),
    ]
