# Generated by Django 3.2.6 on 2021-09-01 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arch", "0019_alter_problem_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="source",
        ),
    ]
