# Generated by Django 3.2.6 on 2021-09-01 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0020_auto_20210901_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='puid',
            field=models.CharField(help_text='Unique problem identifier, as printed in OTIS handout.', max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message="Only uppercase letters and digits appear in PUID's.", regex='[A-Z0-9]+')], verbose_name='PUID'),
        ),
    ]
