# Generated by Django 4.0.7 on 2022-09-26 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arch", "0025_alter_hint_id_alter_problem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="puid",
            field=models.CharField(
                help_text="Problem identifier, as printed in OTIS. Capital letters and digits only.",
                max_length=24,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only uppercase letters and digits appear in PUID's.",
                        regex="^[A-Z0-9]+$",
                    )
                ],
                verbose_name="PUID",
            ),
        ),
    ]
