# Generated by Django 4.1.6 on 2023-02-08 20:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("arch", "0027_problem_hyperlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niceness",
                    models.FloatField(
                        help_text="A student submitted number from 0 to 10 used to indicate the approximate niceness of a problem.",
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="The container of the current vote.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arch.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who voted for this problem.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
