# Generated by Django 4.1.5 on 2023-02-08 06:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("arch", "0027_problem_hyperlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveIntegerField(
                        help_text="A number from 0 to 50 used to indicate the approximate MOHS of a difficulty.",
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="The container of the current vote.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arch.problem",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who voted for this problem.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
