# Generated by Django 4.1.5 on 2023-02-08 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arch", "0028_vote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="difficulty",
        ),
        migrations.AddField(
            model_name="vote",
            name="mohs",
            field=models.PositiveIntegerField(
                default=3,
                help_text="A number from 0 to 50 used to indicate the approximate MOHS of a problem.",
                validators=[django.core.validators.MaxValueValidator(50)],
            ),
            preserve_default=False,
        ),
    ]
