# Generated by Django 4.1.6 on 2023-02-08 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arch", "0028_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="niceness",
            field=models.FloatField(
                help_text="A student submitted number from 0 to 10 used to indicate the approximate niceness of a problem.",
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
