# Generated by Django 4.1.5 on 2023-02-08 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("arch", "0029_remove_vote_difficulty_vote_mohs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                help_text="User who voted for this problem.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
