# Generated by Django 4.1.10 on 2023-08-08 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arch", "0031_vote_created_at_vote_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="puid",
            field=models.CharField(
                help_text="Problem identifier, as printed in OTIS. Capital letters and digits only.",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only uppercase letters and digits appear in PUID's.",
                        regex="^[A-Z0-9]+$",
                    )
                ],
                verbose_name="PUID",
            ),
        ),
    ]
