# Generated by Django 6.0.8 on 2026-09-15 21:10

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0073_rename_userprofile_email_on_petition_complete"),
        ("roster", "0122_studentregistration_us_state"),
        ("rpg", "0022_set_new_unlocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="For example, Survey 1", max_length=80),
                ),
                ("opens_at", models.DateTimeField(help_text="When submissions open")),
                ("closes_at", models.DateTimeField(help_text="When submissions close")),
                (
                    "essay_prompt",
                    models.TextField(help_text="Prompt for the required GM essay"),
                ),
                (
                    "satisfaction_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Prompt for the satisfaction scale; leave blank to not ask",
                    ),
                ),
                (
                    "anything_else_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Prompt for anything else for the GM; leave blank to not ask",
                    ),
                ),
                (
                    "instructor_comments_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Prompt for comments to the instructor; leave blank to not ask",
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Achievement granted for submitting, if the student lacks it",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rpg.achievement",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="The semester whose students take this survey",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.semester",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstructorComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comments", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNREAD", "Unread"),
                            ("FORWARDED", "Forwarded"),
                            ("WITHHELD", "Withheld"),
                        ],
                        default="UNREAD",
                        max_length=9,
                    ),
                ),
                (
                    "assistant",
                    models.ForeignKey(
                        help_text="The student's assistant at the time of submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roster.assistant",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="The student who signed these comments, or empty if anonymous",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roster.student",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GMFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("essay", models.TextField()),
                (
                    "satisfaction",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Satisfaction from 0 to 7, if the survey asked",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(7)],
                    ),
                ),
                ("anything_else", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "reply",
                    models.TextField(
                        blank=True, help_text="Reply shown to the student, if signed"
                    ),
                ),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="The student who signed this feedback, or empty if anonymous",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roster.student",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GM feedback",
            },
        ),
        migrations.CreateModel(
            name="SurveyCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roster.student"
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="survey",
            constraint=models.CheckConstraint(
                condition=models.Q(("opens_at__lt", models.F("closes_at"))),
                name="surveys_survey_opens_before_closes",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveycompletion",
            unique_together={("survey", "student")},
        ),
    ]
