# Generated by Django 6.0.8 on 2026-09-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmfeedback",
            name="token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Secret in the private link to anonymous feedback and its reply, if the student asked for one",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="gmfeedback",
            name="reply",
            field=models.TextField(blank=True, help_text="Reply shown to the student"),
        ),
    ]
