# Generated by Django 6.0.8 on 2026-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_gmfeedback_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="achievement_awarded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the achievement was granted in bulk, if it has been",
                null=True,
            ),
        ),
    ]
