# Generated by Django 4.1.5 on 2023-01-12 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="active",
        ),
        migrations.RemoveField(
            model_name="bonuslevel",
            name="active",
        ),
    ]
