# Generated by Django 4.1.5 on 2023-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0002_remove_achievement_active_remove_bonuslevel_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questcomplete",
            name="category",
            field=models.CharField(
                choices=[
                    ("PR", "Pull request"),
                    ("BR", "Bug report"),
                    ("VD", "Vulnerability disclosure"),
                    ("WK", "Wiki bonus"),
                    ("US", "USEMO Score"),
                    ("UG", "USEMO Grading"),
                    ("MS", "Miscellaneous"),
                ],
                default="MS",
                max_length=4,
            ),
        ),
    ]
