# Generated by Django 4.1.7 on 2023-03-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0003_alter_questcomplete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="alttext",
            field=models.TextField(
                blank=True,
                help_text="A memorable text that is displayed",
                max_length=255,
            ),
        ),
    ]
