# Generated by Django 4.1.7 on 2023-03-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0004_level_alttext"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="show_solution",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, the solution page for a diamond is available to those who have unlocked the diamond.",
                verbose_name="Reveal",
            ),
        ),
    ]
