# Generated by Django 4.2.4 on 2023-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0006_alter_achievement_always_show_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="show_creator",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the creator of a diamond is shown on the diamond page.",
                verbose_name="Show Creator",
            ),
        ),
    ]
