# Generated by Django 4.2.9 on 2024-01-04 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0009_alter_vulnerabilityrecord_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=96,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="24-26 char hex string", regex="^[a-f0-9]{24,26}$"
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
