# Generated by Django 5.0.7 on 2024-07-28 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0011_alter_achievement_id_alter_achievementunlock_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="achievement",
            table=None,
        ),
        migrations.AlterModelTable(
            name="achievementunlock",
            table=None,
        ),
        migrations.AlterModelTable(
            name="bonuslevel",
            table=None,
        ),
        migrations.AlterModelTable(
            name="bonuslevelunlock",
            table=None,
        ),
        migrations.AlterModelTable(
            name="level",
            table=None,
        ),
        migrations.AlterModelTable(
            name="palacecarving",
            table=None,
        ),
        migrations.AlterModelTable(
            name="questcomplete",
            table=None,
        ),
    ]
