# Generated by Django 5.0.7 on 2024-07-28 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rpg",
            "0001_initial_squashed_0013_alter_achievement_id_alter_achievementunlock_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=96,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="24-26 char hex string", regex="^[a-f0-9]{24,26}$"
                    )
                ],
            ),
        ),
    ]
