# Generated by Django 5.1.7 on 2025-03-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0014_alter_achievement_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questcomplete",
            name="spades",
            field=models.SmallIntegerField(help_text="The number of spades granted"),
        ),
    ]
