# Generated by Django 5.2.11 on 2026-03-01 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0015_alter_questcomplete_spades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="code",
            field=models.CharField(
                max_length=96,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="24-26 char hex string", regex="^[a-f0-9]{24,26}$"
                    )
                ],
            ),
        ),
    ]
