# Generated by Django 5.2.11 on 2026-03-01 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0016_alter_achievement_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="special_effect_id",
            field=models.SlugField(
                blank=True,
                default=None,
                help_text="A unique identifier for this particular achievement. Useful if you want to have some special effects associated to it.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="achievement",
            constraint=models.CheckConstraint(
                condition=models.Q(("special_effect_id", ""), _negated=True),
                name="rpg_achievement_special_effect_id_not_empty",
            ),
        ),
    ]
