# Generated by Django 5.2 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0016_alter_achievement_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementunlock",
            name="is_first_obtain",
            field=models.BooleanField(
                default=False,
                help_text="Whether this was the first time this achievement was obtained by a non-creator.",
            ),
        ),
    ]
