# Generated by Django 5.2.16 on 2026-08-02 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0019_set_first_obtains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementCodeGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The code that was submitted, truncated if it was overlong",
                        max_length=96,
                    ),
                ),
                (
                    "is_well_formed",
                    models.BooleanField(
                        help_text="Whether the code was a hex string of the right length; if not, it was never checked against any achievement"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="Whether the code matched an achievement when it was submitted"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time the guess was submitted"
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        blank=True,
                        help_text="The achievement the code matched, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rpg.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who submitted the guess",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Achievement code guesses",
                "indexes": [
                    models.Index(
                        fields=["user", "is_correct", "timestamp"],
                        name="rpg_achieve_user_id_00f8ea_idx",
                    )
                ],
            },
        ),
    ]
