# Generated by Django 5.2.16 on 2026-08-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0020_achievementcodeguess"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementcodeguess",
            name="is_new_unlock",
            field=models.BooleanField(
                default=False,
                help_text="Whether this guess actually earned the achievement, as opposed to re-entering a code the user had already redeemed",
            ),
        ),
    ]
