# Generated by Django 6.0.8 on 2026-09-23 23:03

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpg", "0022_set_new_unlocks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="code",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Code students enter to unlock this achievement. Leave blank for achievements that are only granted directly.",
                max_length=96,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="24-26 char hex string", regex="^[a-f0-9]{24,26}$"
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="achievement",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="rpg_achievement_code_not_empty",
            ),
        ),
    ]
