# Generated by Django 5.2.16 on 2026-07-30 19:29

import django.core.validators
import django.db.models.deletion
import markdownfield.models
from django.conf import settings
from django.db import migrations, models

import yearbook.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YearbookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text='A short one-liner shown next to your name, at most 64 characters. For example, "just another otter".',
                        max_length=64,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AFG", "Afghanistan (AFG)"),
                            ("AGO", "Angola (AGO)"),
                            ("ALB", "Albania (ALB)"),
                            ("ALG", "Algeria (ALG)"),
                            ("ARG", "Argentina (ARG)"),
                            ("ARM", "Armenia (ARM)"),
                            ("AUS", "Australia (AUS)"),
                            ("AUT", "Austria (AUT)"),
                            ("AZE", "Azerbaijan (AZE)"),
                            ("BAH", "Bahrain (BAH)"),
                            ("BEL", "Belgium (BEL)"),
                            ("BEN", "Benin (BEN)"),
                            ("BFA", "Burkina Faso (BFA)"),
                            ("BGD", "Bangladesh (BGD)"),
                            ("BGR", "Bulgaria (BGR)"),
                            ("BIH", "Bosnia and Herzegovina (BIH)"),
                            ("BLR", "Belarus (BLR)"),
                            ("BOL", "Bolivia (BOL)"),
                            ("BRA", "Brazil (BRA)"),
                            ("BRU", "Brunei (BRU)"),
                            ("BTN", "Bhutan (BTN)"),
                            ("BWA", "Botswana (BWA)"),
                            ("CAN", "Canada (CAN)"),
                            ("CHI", "Chile (CHI)"),
                            ("CHN", "People's Republic of China (CHN)"),
                            ("CIS", "Commonwealth of Independent States (CIS)"),
                            ("CIV", "Ivory Coast (CIV)"),
                            ("CMR", "Cameroon (CMR)"),
                            ("COL", "Colombia (COL)"),
                            ("CRI", "Costa Rica (CRI)"),
                            ("CUB", "Cuba (CUB)"),
                            ("CYP", "Cyprus (CYP)"),
                            ("CZE", "Czech Republic (CZE)"),
                            ("CZS", "Czechoslovakia (CZS)"),
                            ("DEN", "Denmark (DEN)"),
                            ("DOM", "Dominican Republic (DOM)"),
                            ("ECU", "Ecuador (ECU)"),
                            ("EGY", "Egypt (EGY)"),
                            ("ESP", "Spain (ESP)"),
                            ("EST", "Estonia (EST)"),
                            ("FIN", "Finland (FIN)"),
                            ("FRA", "France (FRA)"),
                            ("GDR", "German Democratic Republic (GDR)"),
                            ("GEO", "Georgia (GEO)"),
                            ("GER", "Germany (GER)"),
                            ("GHA", "Ghana (GHA)"),
                            ("GMB", "Gambia (GMB)"),
                            ("GTM", "Guatemala (GTM)"),
                            ("HEL", "Greece (HEL)"),
                            ("HKG", "Hong Kong (HKG)"),
                            ("HND", "Honduras (HND)"),
                            ("HRV", "Croatia (HRV)"),
                            ("HUN", "Hungary (HUN)"),
                            ("IDN", "Indonesia (IDN)"),
                            ("IND", "India (IND)"),
                            ("IRL", "Ireland (IRL)"),
                            ("IRN", "Islamic Republic of Iran (IRN)"),
                            ("IRQ", "Iraq (IRQ)"),
                            ("ISL", "Iceland (ISL)"),
                            ("ISR", "Israel (ISR)"),
                            ("ITA", "Italy (ITA)"),
                            ("JAM", "Jamaica (JAM)"),
                            ("JPN", "Japan (JPN)"),
                            ("KAZ", "Kazakhstan (KAZ)"),
                            ("KEN", "Kenya (KEN)"),
                            ("KGZ", "Kyrgyzstan (KGZ)"),
                            ("KHM", "Cambodia (KHM)"),
                            ("KOR", "Republic of Korea (KOR)"),
                            ("KSV", "Kosovo (KSV)"),
                            ("KWT", "Kuwait (KWT)"),
                            ("LAO", "Laos (LAO)"),
                            ("LBY", "Libya (LBY)"),
                            ("LIE", "Liechtenstein (LIE)"),
                            ("LKA", "Sri Lanka (LKA)"),
                            ("LTU", "Lithuania (LTU)"),
                            ("LUX", "Luxembourg (LUX)"),
                            ("LVA", "Latvia (LVA)"),
                            ("MAC", "Macau (MAC)"),
                            ("MAR", "Morocco (MAR)"),
                            ("MAS", "Malaysia (MAS)"),
                            ("MDA", "Republic of Moldova (MDA)"),
                            ("MDG", "Madagascar (MDG)"),
                            ("MEX", "Mexico (MEX)"),
                            ("MKD", "North Macedonia (MKD)"),
                            ("MMR", "Myanmar (MMR)"),
                            ("MNE", "Montenegro (MNE)"),
                            ("MNG", "Mongolia (MNG)"),
                            ("MOZ", "Mozambique (MOZ)"),
                            ("MRT", "Mauritania (MRT)"),
                            ("NAM", "Namibia (NAM)"),
                            ("NCY", "Turkish Republic of Northern Cyprus (NCY)"),
                            ("NGA", "Nigeria (NGA)"),
                            ("NIC", "Nicaragua (NIC)"),
                            ("NLD", "Netherlands (NLD)"),
                            ("NOR", "Norway (NOR)"),
                            ("NPL", "Nepal (NPL)"),
                            ("NZL", "New Zealand (NZL)"),
                            ("OMN", "Oman (OMN)"),
                            ("PAK", "Pakistan (PAK)"),
                            ("PAN", "Panama (PAN)"),
                            ("PAR", "Paraguay (PAR)"),
                            ("PER", "Peru (PER)"),
                            ("PHI", "Philippines (PHI)"),
                            ("POL", "Poland (POL)"),
                            ("POR", "Portugal (POR)"),
                            ("PRI", "Puerto Rico (PRI)"),
                            ("PRK", "Democratic People's Republic of Korea (PRK)"),
                            ("PSE", "Palestine (PSE)"),
                            ("QAT", "Qatar (QAT)"),
                            ("ROU", "Romania (ROU)"),
                            ("RUS", "Russian Federation (RUS)"),
                            ("RWA", "Rwanda (RWA)"),
                            ("SAF", "South Africa (SAF)"),
                            ("SAU", "Saudi Arabia (SAU)"),
                            ("SCG", "Serbia and Montenegro (SCG)"),
                            ("SEN", "Senegal (SEN)"),
                            ("SGP", "Singapore (SGP)"),
                            ("SLV", "El Salvador (SLV)"),
                            ("SRB", "Serbia (SRB)"),
                            ("SUI", "Switzerland (SUI)"),
                            ("SVK", "Slovakia (SVK)"),
                            ("SVN", "Slovenia (SVN)"),
                            ("SWE", "Sweden (SWE)"),
                            ("SYR", "Syria (SYR)"),
                            ("THA", "Thailand (THA)"),
                            ("TJK", "Tajikistan (TJK)"),
                            ("TKM", "Turkmenistan (TKM)"),
                            ("TTO", "Trinidad and Tobago (TTO)"),
                            ("TUN", "Tunisia (TUN)"),
                            ("TUR", "Türkiye (TUR)"),
                            ("TWN", "Taiwan (TWN)"),
                            ("TZA", "Tanzania (TZA)"),
                            ("UAE", "United Arab Emirates (UAE)"),
                            ("UGA", "Uganda (UGA)"),
                            ("UKR", "Ukraine (UKR)"),
                            ("UNK", "United Kingdom (UNK)"),
                            ("URY", "Uruguay (URY)"),
                            ("USA", "United States of America (USA)"),
                            ("USS", "Union of Soviet Socialist Republics (USS)"),
                            ("UZB", "Uzbekistan (UZB)"),
                            ("VEN", "Venezuela (VEN)"),
                            ("VNM", "Vietnam (VNM)"),
                            ("YEM", "Yemen (YEM)"),
                            ("YUG", "Yugoslavia (YUG)"),
                            ("ZWE", "Zimbabwe (ZWE)"),
                        ],
                        help_text="The country you would like shown next to your name.",
                        max_length=6,
                    ),
                ),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The year you graduated (or expect to graduate) from high school. Leave blank to not show this.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="High school graduation year",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="A small picture of yourself, no more than 1 megabyte. It gets displayed as a square thumbnail, so a square image works best.",
                        null=True,
                        upload_to=yearbook.models.avatar_file_name,
                        validators=[
                            yearbook.models.validate_at_most_1mb,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "gif", "webp"]
                            ),
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="An email address other OTIS folks can reach you at. Leave blank to not show one.",
                        max_length=254,
                    ),
                ),
                (
                    "discord_username",
                    models.CharField(
                        blank=True,
                        help_text="Your Discord handle, without the leading @.",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, digits, and the characters . _ - are allowed.",
                                regex="^[A-Za-z0-9._-]+$",
                            )
                        ],
                        verbose_name="Discord username",
                    ),
                ),
                (
                    "github_username",
                    models.CharField(
                        blank=True,
                        help_text="Your GitHub username, without the leading @.",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, digits, and the characters . _ - are allowed.",
                                regex="^[A-Za-z0-9._-]+$",
                            )
                        ],
                        verbose_name="GitHub username",
                    ),
                ),
                (
                    "aops_username",
                    models.CharField(
                        blank=True,
                        help_text="Your Art of Problem Solving username.",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, digits, and the characters . _ - are allowed.",
                                regex="^[A-Za-z0-9._-]+$",
                            )
                        ],
                        verbose_name="AoPS username",
                    ),
                ),
                (
                    "instagram_username",
                    models.CharField(
                        blank=True,
                        help_text="Your Instagram handle, without the leading @.",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only letters, digits, and the characters . _ - are allowed.",
                                regex="^[A-Za-z0-9._-]+$",
                            )
                        ],
                        verbose_name="Instagram username",
                    ),
                ),
                (
                    "imo_years",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated years you competed at the IMO, e.g. 2023, 2024.",
                        max_length=128,
                        validators=[yearbook.models.validate_year_list],
                        verbose_name="IMO participations",
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True,
                        help_text="The university you attend or attended, if any.",
                        max_length=128,
                    ),
                ),
                (
                    "bio",
                    markdownfield.models.MarkdownField(
                        blank=True,
                        help_text="Write as much or as little about yourself as you'd like, in Markdown. This is the main body of your yearbook page.",
                        rendered_field="bio_rendered",
                        verbose_name="Personal page",
                    ),
                ),
                ("bio_rendered", markdownfield.models.RenderedMarkdownField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The person this yearbook entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearbook_entry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "yearbook entry",
                "verbose_name_plural": "yearbook entries",
                "ordering": ("user__first_name", "user__last_name", "user__username"),
            },
        ),
    ]
