# Generated by Django 5.2.16 on 2026-08-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yearbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearbookentry",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="While this is checked, your page is hidden from the yearbook; only you and OTIS staff can see it. Useful if you want to write your page over several sittings.",
                verbose_name="Draft mode",
            ),
        ),
    ]
