# Generated by Django 5.2.16 on 2026-08-01 17:56

from django.db import migrations, models

import yearbook.models


class Migration(migrations.Migration):
    dependencies = [
        ("yearbook", "0002_yearbookentry_is_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearbookentry",
            name="aops_username",
            field=models.CharField(
                blank=True,
                help_text="Your Art of Problem Solving username.",
                max_length=64,
                validators=[yearbook.models.validate_username],
                verbose_name="AoPS username",
            ),
        ),
        migrations.AlterField(
            model_name="yearbookentry",
            name="discord_username",
            field=models.CharField(
                blank=True,
                help_text="Your Discord handle, without the leading @.",
                max_length=64,
                validators=[yearbook.models.validate_username],
                verbose_name="Discord username",
            ),
        ),
        migrations.AlterField(
            model_name="yearbookentry",
            name="github_username",
            field=models.CharField(
                blank=True,
                help_text="Your GitHub username, without the leading @.",
                max_length=64,
                validators=[yearbook.models.validate_username],
                verbose_name="GitHub username",
            ),
        ),
        migrations.AlterField(
            model_name="yearbookentry",
            name="instagram_username",
            field=models.CharField(
                blank=True,
                help_text="Your Instagram handle, without the leading @.",
                max_length=64,
                validators=[yearbook.models.validate_username],
                verbose_name="Instagram username",
            ),
        ),
        migrations.AlterField(
            model_name="yearbookentry",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="While this is checked, your page is hidden from the yearbook; only you and OTIS staff can see it. Use this to draft your page before publishing it, or to quietly take yourself out of the yearbook later without losing anything you wrote.",
                verbose_name="Draft mode",
            ),
        ),
    ]
