# Generated by Django 5.2.16 on 2026-08-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yearbook", "0003_alter_yearbookentry_aops_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yearbookentry",
            name="imo_years",
        ),
        migrations.AddField(
            model_name="yearbookentry",
            name="imo_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If you attended the IMO, you can list your contestant ID number here. It is the number in the URL of your page on the IMO website, e.g. 24870 for imo-official.org/results/contestant/24870/.",
                null=True,
                verbose_name="IMO ID",
            ),
        ),
        migrations.AddField(
            model_name="yearbookentry",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="A personal website or blog, if you have one.",
                max_length=128,
            ),
        ),
    ]
