# Generated by Django 4.1.7 on 2023-03-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opalhunt",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Whether to highlight this hunt on the list."
            ),
        ),
    ]
