# Generated by Django 4.1.7 on 2023-03-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0002_alter_opalhunt_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opalhunt",
            name="author_draft_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Authors need to have drafts of their puzzles done by this date.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opalhunt",
            name="author_signup_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Authors need to sign up by this date.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="opalhunt",
            name="author_signup_url",
            field=models.URLField(
                blank=True, help_text="Link to signup form for authors"
            ),
        ),
    ]
