# Generated by Django 5.0.7 on 2024-07-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0004_opalpuzzle_opalattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opalpuzzle",
            name="num_to_unlock",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of solves needed before this OPAL puzzle is unlocked",
            ),
        ),
    ]
