# Generated by Django 5.0.7 on 2024-07-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0004_opalpuzzle_opalattempt"),
        ("rpg", "0013_alter_achievement_id_alter_achievementunlock_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opalpuzzle",
            name="achievement",
            field=models.ForeignKey(
                blank=True,
                help_text="Achievement to be awarded if this puzzle is solved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rpg.achievement",
            ),
        ),
    ]
