# Generated by Django 5.0.7 on 2024-07-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0006_opalpuzzle_guess_limit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opalpuzzle",
            options={"ordering": ("hunt__start_date", "num_to_unlock", "title")},
        ),
        migrations.AddField(
            model_name="opalpuzzle",
            name="is_metapuzzle",
            field=models.BooleanField(
                default=False, help_text="Whether this is a metapuzzle or not"
            ),
        ),
        migrations.AlterField(
            model_name="opalhunt",
            name="slug",
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="opalpuzzle",
            unique_together={("hunt", "slug")},
        ),
    ]
