# Generated by Django 5.0.7 on 2024-07-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0007_alter_opalpuzzle_options_opalpuzzle_is_metapuzzle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opalattempt",
            name="excused",
            field=models.BooleanField(
                default=False,
                help_text="Allows admins to maker a guess as not counting towards the guess limit.",
            ),
        ),
    ]
