# Generated by Django 5.0.7 on 2024-07-29 22:59

import markdownfield.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0008_opalattempt_excused"),
    ]

    operations = [
        migrations.AddField(
            model_name="opalhunt",
            name="story_text",
            field=markdownfield.models.MarkdownField(
                blank=True,
                help_text="Text to show on the round page.",
                rendered_field="story_text_rendered",
            ),
        ),
        migrations.AddField(
            model_name="opalhunt",
            name="story_text_rendered",
            field=markdownfield.models.RenderedMarkdownField(default=""),
            preserve_default=False,
        ),
    ]
