# Generated by Django 5.0.8 on 2024-08-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0009_opalhunt_story_text_opalhunt_story_text_rendered"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opalpuzzle",
            options={"ordering": ("hunt__start_date", "order", "num_to_unlock")},
        ),
        migrations.AddField(
            model_name="opalpuzzle",
            name="credits",
            field=models.CharField(
                blank=True,
                help_text="Credits for the author of the puzzle.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="opalpuzzle",
            name="order",
            field=models.SmallIntegerField(
                default=0,
                help_text="The order to display the puzzle in within the hunt.",
            ),
        ),
    ]
