# Generated by Django 5.1 on 2024-08-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0010_alter_opalpuzzle_options_opalpuzzle_credits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opalpuzzle",
            name="errata",
            field=models.TextField(blank=True, help_text="For announcing errata"),
        ),
    ]
