# Generated by Django 5.1 on 2024-09-01 16:27

import django.utils.timezone
import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0011_opalpuzzle_errata"),
    ]

    operations = [
        migrations.AddField(
            model_name="opalhunt",
            name="hints_released_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When to start showing hints.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opalpuzzle",
            name="hint_text",
            field=markdownfield.models.MarkdownField(
                blank=True,
                help_text="List of canned hints for this puzzle.",
                rendered_field="hint_text_rendered",
            ),
        ),
        migrations.AddField(
            model_name="opalpuzzle",
            name="hint_text_rendered",
            field=markdownfield.models.RenderedMarkdownField(default=""),
            preserve_default=False,
        ),
    ]
