# Generated by Django 5.2.4 on 2025-08-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0013_opalattempt_is_close_opalpuzzle_partial_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="opalhunt",
            name="thanks",
            field=models.TextField(
                blank=True, help_text="Thanks to people who helped."
            ),
        ),
    ]
