# Generated by Django 5.2.4 on 2025-09-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0014_opalhunt_thanks"),
    ]

    operations = [
        migrations.AddField(
            model_name="opalhunt",
            name="discord_webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Webhook to post to congratulating people who finish the hunt.",
            ),
        ),
    ]
