# Generated by Django 5.2.5 on 2025-09-07 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0015_opalhunt_discord_webhook_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opalhunt",
            options={"ordering": ("start_date",)},
        ),
    ]
