# Generated by Django 6.0.7 on 2026-08-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0016_alter_opalhunt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opalhunt",
            name="discord_webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Webhook to post to congratulate people who finish the hunt.",
            ),
        ),
    ]
