# Generated by Django 6.0.8 on 2026-08-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0017_alter_opalhunt_discord_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="opalhunt",
            name="artwork_slug",
            field=models.CharField(
                blank=True,
                help_text="Filename (without extension) of the artwork for this hunt on the gallery CDN, like 'opal3'. Leave blank to show a placeholder.",
                max_length=64,
            ),
        ),
    ]
