# Generated by Django 6.0.8 on 2026-08-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opal", "0018_opalhunt_artwork_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="opalpuzzle",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of the puzzle file, so a bulk sync can skip PDFs whose bytes did not change. Blank means unknown, which makes the sync re-upload.",
                max_length=64,
            ),
        ),
    ]
