# Generated by Django 4.1.5 on 2023-02-02 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hanabi", "0002_remove_hanabicontest_variant_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hanabiplayer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
