# Generated by Django 4.1.5 on 2023-02-02 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hanabi", "0003_hanabiplayer_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hanabireplay",
            old_name="spade_score",
            new_name="spades_score",
        ),
    ]
