# Generated by Django 4.1.5 on 2023-02-02 16:47

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hanabi", "0005_hanabicontest_processed_hanabicontest_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hanabicontest",
            options={"ordering": ("-end_date",)},
        ),
        migrations.RemoveField(
            model_name="hanabicontest",
            name="deadline",
        ),
        migrations.AddField(
            model_name="hanabicontest",
            name="end_date",
            field=models.DateTimeField(
                default=timezone.datetime(2099, 1, 1, 0, 0, tzinfo=timezone.utc),
                help_text="The end_date to play this seed.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hanabicontest",
            name="num_players",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="The number of players."
            ),
        ),
    ]
