COUNTRY_CHOICES = (
    ("AFG", "Afghanistan (AFG)"),
    ("AGO", "Angola (AGO)"),
    ("ALB", "Albania (ALB)"),
    ("ALG", "Algeria (ALG)"),
    ("ARG", "Argentina (ARG)"),
    ("ARM", "Armenia (ARM)"),
    ("AUS", "Australia (AUS)"),
    ("AUT", "Austria (AUT)"),
    ("AZE", "Azerbaijan (AZE)"),
    ("BAH", "Bahrain (BAH)"),
    ("BEL", "Belgium (BEL)"),
    ("BEN", "Benin (BEN)"),
    ("BFA", "Burkina Faso (BFA)"),
    ("BGD", "Bangladesh (BGD)"),
    ("BGR", "Bulgaria (BGR)"),
    ("BIH", "Bosnia and Herzegovina (BIH)"),
    ("BLR", "Belarus (BLR)"),
    ("BOL", "Bolivia (BOL)"),
    ("BRA", "Brazil (BRA)"),
    ("BRU", "Brunei (BRU)"),
    ("BTN", "Bhutan (BTN)"),
    ("BWA", "Botswana (BWA)"),
    ("CAN", "Canada (CAN)"),
    ("CHI", "Chile (CHI)"),
    ("CHN", "People's Republic of China (CHN)"),
    ("CIS", "Commonwealth of Independent States (CIS)"),
    ("CIV", "Ivory Coast (CIV)"),
    ("CMR", "Cameroon (CMR)"),
    ("COL", "Colombia (COL)"),
    ("CRI", "Costa Rica (CRI)"),
    ("CUB", "Cuba (CUB)"),
    ("CYP", "Cyprus (CYP)"),
    ("CZE", "Czech Republic (CZE)"),
    ("CZS", "Czechoslovakia (CZS)"),
    ("DEN", "Denmark (DEN)"),
    ("DOM", "Dominican Republic (DOM)"),
    ("ECU", "Ecuador (ECU)"),
    ("EGY", "Egypt (EGY)"),
    ("ESP", "Spain (ESP)"),
    ("EST", "Estonia (EST)"),
    ("FIN", "Finland (FIN)"),
    ("FRA", "France (FRA)"),
    ("GDR", "German Democratic Republic (GDR)"),
    ("GEO", "Georgia (GEO)"),
    ("GER", "Germany (GER)"),
    ("GHA", "Ghana (GHA)"),
    ("GMB", "Gambia (GMB)"),
    ("GTM", "Guatemala (GTM)"),
    ("HEL", "Greece (HEL)"),
    ("HKG", "Hong Kong (HKG)"),
    ("HND", "Honduras (HND)"),
    ("HRV", "Croatia (HRV)"),
    ("HUN", "Hungary (HUN)"),
    ("IDN", "Indonesia (IDN)"),
    ("IND", "India (IND)"),
    ("IRL", "Ireland (IRL)"),
    ("IRN", "Islamic Republic of Iran (IRN)"),
    ("IRQ", "Iraq (IRQ)"),
    ("ISL", "Iceland (ISL)"),
    ("ISR", "Israel (ISR)"),
    ("ITA", "Italy (ITA)"),
    ("JAM", "Jamaica (JAM)"),
    ("JPN", "Japan (JPN)"),
    ("KAZ", "Kazakhstan (KAZ)"),
    ("KEN", "Kenya (KEN)"),
    ("KGZ", "Kyrgyzstan (KGZ)"),
    ("KHM", "Cambodia (KHM)"),
    ("KOR", "Republic of Korea (KOR)"),
    ("KSV", "Kosovo (KSV)"),
    ("KWT", "Kuwait (KWT)"),
    ("LAO", "Laos (LAO)"),
    ("LBY", "Libya (LBY)"),
    ("LIE", "Liechtenstein (LIE)"),
    ("LKA", "Sri Lanka (LKA)"),
    ("LTU", "Lithuania (LTU)"),
    ("LUX", "Luxembourg (LUX)"),
    ("LVA", "Latvia (LVA)"),
    ("MAC", "Macau (MAC)"),
    ("MAR", "Morocco (MAR)"),
    ("MAS", "Malaysia (MAS)"),
    ("MDA", "Republic of Moldova (MDA)"),
    ("MDG", "Madagascar (MDG)"),
    ("MEX", "Mexico (MEX)"),
    ("MKD", "North Macedonia (MKD)"),
    ("MMR", "Myanmar (MMR)"),
    ("MNE", "Montenegro (MNE)"),
    ("MNG", "Mongolia (MNG)"),
    ("MOZ", "Mozambique (MOZ)"),
    ("MRT", "Mauritania (MRT)"),
    ("NAM", "Namibia (NAM)"),
    ("NCY", "Turkish Republic of Northern Cyprus (NCY)"),
    ("NGA", "Nigeria (NGA)"),
    ("NIC", "Nicaragua (NIC)"),
    ("NLD", "Netherlands (NLD)"),
    ("NOR", "Norway (NOR)"),
    ("NPL", "Nepal (NPL)"),
    ("NZL", "New Zealand (NZL)"),
    ("OMN", "Oman (OMN)"),
    ("PAK", "Pakistan (PAK)"),
    ("PAN", "Panama (PAN)"),
    ("PAR", "Paraguay (PAR)"),
    ("PER", "Peru (PER)"),
    ("PHI", "Philippines (PHI)"),
    ("POL", "Poland (POL)"),
    ("POR", "Portugal (POR)"),
    ("PRI", "Puerto Rico (PRI)"),
    ("PRK", "Democratic People's Republic of Korea (PRK)"),
    ("PSE", "Palestine (PSE)"),
    ("QAT", "Qatar (QAT)"),
    ("ROU", "Romania (ROU)"),
    ("RUS", "Russian Federation (RUS)"),
    ("RWA", "Rwanda (RWA)"),
    ("SAF", "South Africa (SAF)"),
    ("SAU", "Saudi Arabia (SAU)"),
    ("SCG", "Serbia and Montenegro (SCG)"),
    ("SEN", "Senegal (SEN)"),
    ("SGP", "Singapore (SGP)"),
    ("SLV", "El Salvador (SLV)"),
    ("SRB", "Serbia (SRB)"),
    ("SUI", "Switzerland (SUI)"),
    ("SVK", "Slovakia (SVK)"),
    ("SVN", "Slovenia (SVN)"),
    ("SWE", "Sweden (SWE)"),
    ("SYR", "Syria (SYR)"),
    ("THA", "Thailand (THA)"),
    ("TJK", "Tajikistan (TJK)"),
    ("TKM", "Turkmenistan (TKM)"),
    ("TTO", "Trinidad and Tobago (TTO)"),
    ("TUN", "Tunisia (TUN)"),
    ("TUR", "Türkiye (TUR)"),
    ("TWN", "Taiwan (TWN)"),
    ("TZA", "Tanzania (TZA)"),
    ("UAE", "United Arab Emirates (UAE)"),
    ("UGA", "Uganda (UGA)"),
    ("UKR", "Ukraine (UKR)"),
    ("UNK", "United Kingdom (UNK)"),
    ("URY", "Uruguay (URY)"),
    ("USA", "United States of America (USA)"),
    ("USS", "Union of Soviet Socialist Republics (USS)"),
    ("UZB", "Uzbekistan (UZB)"),
    ("VEN", "Venezuela (VEN)"),
    ("VNM", "Vietnam (VNM)"),
    ("YEM", "Yemen (YEM)"),
    ("YUG", "Yugoslavia (YUG)"),
    ("ZWE", "Zimbabwe (ZWE)"),
)

# The keys above are IMO-style abbreviations, which do not always agree with
# ISO 3166-1. This maps them to the ISO 3166-1 alpha-2 codes that the Unicode
# regional indicator symbols (i.e. flag emoji) are built out of.
# Countries which no longer exist have no entry here.
COUNTRY_ISO_ALPHA2 = {
    "AFG": "AF",
    "AGO": "AO",
    "ALB": "AL",
    "ALG": "DZ",
    "ARG": "AR",
    "ARM": "AM",
    "AUS": "AU",
    "AUT": "AT",
    "AZE": "AZ",
    "BAH": "BH",
    "BEL": "BE",
    "BEN": "BJ",
    "BFA": "BF",
    "BGD": "BD",
    "BGR": "BG",
    "BIH": "BA",
    "BLR": "BY",
    "BOL": "BO",
    "BRA": "BR",
    "BRU": "BN",
    "BTN": "BT",
    "BWA": "BW",
    "CAN": "CA",
    "CHI": "CL",
    "CHN": "CN",
    "CIV": "CI",
    "CMR": "CM",
    "COL": "CO",
    "CRI": "CR",
    "CUB": "CU",
    "CYP": "CY",
    "CZE": "CZ",
    "DEN": "DK",
    "DOM": "DO",
    "ECU": "EC",
    "EGY": "EG",
    "ESP": "ES",
    "EST": "EE",
    "FIN": "FI",
    "FRA": "FR",
    "GEO": "GE",
    "GER": "DE",
    "GHA": "GH",
    "GMB": "GM",
    "GTM": "GT",
    "HEL": "GR",
    "HKG": "HK",
    "HND": "HN",
    "HRV": "HR",
    "HUN": "HU",
    "IDN": "ID",
    "IND": "IN",
    "IRL": "IE",
    "IRN": "IR",
    "IRQ": "IQ",
    "ISL": "IS",
    "ISR": "IL",
    "ITA": "IT",
    "JAM": "JM",
    "JPN": "JP",
    "KAZ": "KZ",
    "KEN": "KE",
    "KGZ": "KG",
    "KHM": "KH",
    "KOR": "KR",
    "KSV": "XK",
    "KWT": "KW",
    "LAO": "LA",
    "LBY": "LY",
    "LIE": "LI",
    "LKA": "LK",
    "LTU": "LT",
    "LUX": "LU",
    "LVA": "LV",
    "MAC": "MO",
    "MAR": "MA",
    "MAS": "MY",
    "MDA": "MD",
    "MDG": "MG",
    "MEX": "MX",
    "MKD": "MK",
    "MMR": "MM",
    "MNE": "ME",
    "MNG": "MN",
    "MOZ": "MZ",
    "MRT": "MR",
    "NAM": "NA",
    "NGA": "NG",
    "NIC": "NI",
    "NLD": "NL",
    "NOR": "NO",
    "NPL": "NP",
    "NZL": "NZ",
    "OMN": "OM",
    "PAK": "PK",
    "PAN": "PA",
    "PAR": "PY",
    "PER": "PE",
    "PHI": "PH",
    "POL": "PL",
    "POR": "PT",
    "PRI": "PR",
    "PRK": "KP",
    "PSE": "PS",
    "QAT": "QA",
    "ROU": "RO",
    "RUS": "RU",
    "RWA": "RW",
    "SAF": "ZA",
    "SAU": "SA",
    "SEN": "SN",
    "SGP": "SG",
    "SLV": "SV",
    "SRB": "RS",
    "SUI": "CH",
    "SVK": "SK",
    "SVN": "SI",
    "SWE": "SE",
    "SYR": "SY",
    "THA": "TH",
    "TJK": "TJ",
    "TKM": "TM",
    "TTO": "TT",
    "TUN": "TN",
    "TUR": "TR",
    "TWN": "TW",
    "TZA": "TZ",
    "UAE": "AE",
    "UGA": "UG",
    "UKR": "UA",
    "UNK": "GB",
    "URY": "UY",
    "USA": "US",
    "UZB": "UZ",
    "VEN": "VE",
    "VNM": "VN",
    "YEM": "YE",
    "ZWE": "ZW",
}

# Strips the trailing parenthetical, e.g. "Australia (AUS)" becomes "Australia"
COUNTRY_NAMES = {code: label[: label.rindex(" (")] for code, label in COUNTRY_CHOICES}

_REGIONAL_INDICATOR_OFFSET = ord("\N{REGIONAL INDICATOR SYMBOL LETTER A}") - ord("A")


def get_country_name(code: str) -> str:
    """Human-readable name for an IMO country abbreviation, or the code itself."""
    return COUNTRY_NAMES.get(code, code)


def get_country_flag(code: str) -> str:
    """Flag emoji for an IMO country abbreviation.

    Returns a globe for countries that predate the current ISO 3166-1 list
    (e.g. Yugoslavia), since no flag emoji exists for those.
    """
    if not code:
        return ""
    alpha2 = COUNTRY_ISO_ALPHA2.get(code)
    if alpha2 is None:
        return "\N{GLOBE WITH MERIDIANS}"
    return "".join(chr(ord(c) + _REGIONAL_INDICATOR_OFFSET) for c in alpha2)


def get_country_imo_url(code: str) -> str:
    """Link to a country's IMO results page.

    The abbreviations above are the ones the IMO itself uses, so this works for
    the defunct countries (Soviet Union, Yugoslavia, ...) too.
    """
    if code not in COUNTRY_NAMES:
        return ""
    return f"https://www.imo-official.org/results/team/country/{code}/"
