# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 00:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20170806_0009"),
        ("roster", "0006_auto_20170806_0035"),
    ]

    operations = [
        migrations.AddField(
            model_name="ta",
            name="semester",
            field=models.ForeignKey(
                default=None,
                help_text="The semester for this TA",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Semester",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="curriculum",
            field=models.ManyToManyField(
                blank=True,
                help_text="The choice of units that this student will work on",
                to="core.Unit",
            ),
        ),
    ]
