# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-06 00:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_auto_20170806_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text='The Django Auth user attached to the student',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ta',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text='The Django Auth user attached to the TA',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
