# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-05 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0013_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="amount_owed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Amount currently owed.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
