# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-25 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0020_assistant_shortname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": (
                    "semester",
                    "-legit",
                    "track",
                    "user__first_name",
                    "user__last_name",
                )
            },
        ),
    ]
