# Generated by Django 2.1.7 on 2019-10-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0027_auto_20191011_1232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitinquiry",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("DROP", "Drop unit"),
                    ("JUMP", "Mark current (and add)"),
                    ("ADD", "Add unit"),
                ],
                help_text="Describe the action you want to make.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="unitinquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACC", "Approved"),
                    ("REJ", "Rejected"),
                    ("NEW", "Pending"),
                    ("HOLD", "On hold"),
                ],
                default="NEW",
                help_text="The current status of the inquiry.",
                max_length=5,
            ),
        ),
    ]
