# Generated by Django 2.1.11 on 2019-12-01 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0029_auto_20191011_1931"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="current_unit_index",
            new_name="num_units_done",
        ),
    ]
