# Generated by Django 2.1.11 on 2019-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0032_student_newborn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="newborn",
            field=models.BooleanField(
                default=True, help_text="Whether the student is newly created."
            ),
        ),
    ]
