# Generated by Django 3.0.3 on 2020-04-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0039_unlock_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='num_units_done',
            field=models.SmallIntegerField(default=0, help_text="The number of completed units. This is set manually for Evan's book-keeping."),
        ),
        migrations.AlterField(
            model_name='student',
            name='vision',
            field=models.SmallIntegerField(default=3, help_text='Deprecated and no longer in use. To be deleted.'),
        ),
    ]
