# Generated by Django 3.0.3 on 2020-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0042_inquiry_type_rename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitinquiry",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("UNLOCK", "Unlock"),
                    ("APPEND", "Add for later"),
                    ("DROP", "Drop"),
                ],
                help_text="Describe the action you want to make.",
                max_length=10,
            ),
        ),
    ]
