# Generated by Django 3.0.3 on 2020-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0043_auto_20200428_0954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitinquiry",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("UNLOCK", "Unlock now"),
                    ("APPEND", "Add for later"),
                    ("DROP", "Drop"),
                ],
                help_text="Describe the action you want to make.",
                max_length=10,
            ),
        ),
    ]
