# Generated by Django 3.1.8 on 2021-04-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0050_auto_20210213_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='Student email address.', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Parent email address.', max_length=254),
        ),
    ]
