# Generated by Django 3.2.5 on 2021-07-27 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import roster.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_unitgroup_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0052_invoice_forgive'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Whether to accept new registrations')),
                ('passcode', models.CharField(help_text="The passcode for that year's registration", max_length=128)),
                ('semester', models.OneToOneField(help_text='Controls the settings for registering for a semester', on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name in American format (given name followed by family name). Middle name is optional.', max_length=192)),
                ('email', models.EmailField(help_text='The email address. Please choose an email you check frequently because all future email communication will be sent to this address.', max_length=254)),
                ('parent_email', models.EmailField(help_text='An email address in case Evan needs to contact your parents or something.', max_length=254)),
                ('track', models.CharField(choices=[('C', 'Correspondence'), ('E', 'Meeting with another instructor'), ('B', 'Meeting with Evan'), ('N', 'None of the above')], max_length=6)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('H', 'Nonbinary'), ('O', 'Other'), ('', 'Prefer not to say')], default='', help_text='If you are comfortable answering, specify which gender you most closely identify with.', max_length=2)),
                ('grade_level', models.IntegerField(choices=[(13, 'Already graduated high school'), (12, 'Graduating in 2022'), (11, 'Graduating in 2023'), (10, 'Graduating in 2024'), (9, 'Graduating in 2025'), (8, 'Graduating in 2026'), (7, 'Graduating in 2027'), (6, 'Graduating in 2028'), (5, 'Graduating in 2029')], help_text='Enter your expected graduation year')),
                ('school_name', models.CharField(help_text='Enter the name of your high school', max_length=200)),
                ('aops_username', models.CharField(blank=True, help_text='Enter your Art of Problem Solving username (leave blank for none)', max_length=200)),
                ('agreement_form', models.FileField(help_text='Signed agreement form, as a single PDF', upload_to=roster.models.content_file_name)),
                ('container', models.ForeignKey(help_text='Where to register for', on_delete=django.db.models.deletion.CASCADE, to='roster.registrationcontainer')),
                ('user', models.ForeignKey(help_text='The user to attach', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
