# Generated by Django 3.2.5 on 2021-08-06 13:55

import django.core.validators
from django.db import migrations, models

import roster.models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0064_auto_20210805_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregistration",
            name="agreement_form",
            field=models.FileField(
                default="MISSING",
                help_text="Signed agreement form, as a single PDF",
                upload_to=roster.models.content_file_name,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
