# Generated by Django 3.2.6 on 2021-08-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0067_remove_student_num_units_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="achievements",
        ),
    ]
