# Generated by Django 3.2.6 on 2021-08-19 15:34

import django.core.validators
from django.db import migrations, models

import roster.models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0068_remove_student_achievements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregistration",
            name="agreement_form",
            field=models.FileField(
                help_text="Signed agreement form, as a single PDF",
                null=True,
                upload_to=roster.models.content_file_name,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
