# Generated by Django 3.2.6 on 2021-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0069_alter_studentregistration_agreement_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={'ordering': ('shortname',)},
        ),
        migrations.AlterField(
            model_name='assistant',
            name='shortname',
            field=models.CharField(
                help_text='Initials or short name for this Assistant', max_length=18),
        ),
    ]
