# Generated by Django 3.2.7 on 2021-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0072_alter_unitinquiry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationcontainer",
            name="num_preps",
            field=models.PositiveSmallIntegerField(
                default=2, help_text="Number of preps to bill for"
            ),
        ),
    ]
