# Generated by Django 3.2.7 on 2021-09-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0074_auto_20210913_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_level_time',
        ),
    ]
