# Generated by Django 3.2.7 on 2021-10-04 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roster", "0076_alter_studentregistration_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregistration",
            name="user",
            field=models.ForeignKey(
                help_text="The user to attach",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
