# Generated by Django 3.2.8 on 2021-10-19 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0078_invoice_forgive_memo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentregistration",
            options={
                "verbose_name": "Unit petition",
                "verbose_name_plural": "Unit petitions",
            },
        ),
    ]
