# Generated by Django 3.2.11 on 2022-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0081_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Allow student to submit/request units.'),
        ),
    ]
