# Generated by Django 3.2.12 on 2022-02-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0083_rename_forgive_memo_invoice_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='memo',
            field=models.TextField(blank=True, help_text='Internal note to self.'),
        ),
    ]
