# Generated by Django 4.0.6 on 2022-08-05 22:03

from django.db import migrations


def gender_update(apps, scheme_editor):
	Regs = apps.get_model('roster', 'StudentRegistration')
	Regs.objects.filter(gender="").update(gender="U")


def do_nothing(apps, scheme_editor):
	pass


class Migration(migrations.Migration):
	dependencies = [
		('roster', '0085_alter_studentregistration_gender_and_more'),
	]

	operations = [migrations.RunPython(gender_update, do_nothing)]
