# Generated by Django 4.0.7 on 2022-08-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0086_auto_20220805_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='public',
            field=models.BooleanField(default=False, help_text='Whether student name appears on public leaderboards, like the diamonds leaderboard.'),
        ),
    ]
