# Generated by Django 4.0.7 on 2022-08-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0088_remove_student_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='public',
            field=models.BooleanField(default=False, help_text='Whether student name appears on public leaderboards, like the diamonds leaderboard.'),
        ),
    ]
