# Generated by Django 4.0.7 on 2022-09-27 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0090_auto_20220927_1628"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationcontainer",
            name="end_year",
        ),
    ]
