# Generated by Django 4.0.8 on 2022-12-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0092_alter_unitinquiry_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='forgive',
        ),
        migrations.AddField(
            model_name='invoice',
            name='forgive_date',
            field=models.DateTimeField(blank=True, help_text="When switched on, won't hard lock delinquents before this date.", null=True),
        ),
    ]
