# Generated by Django 4.0.8 on 2022-12-22 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0095_alter_unitinquiry_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentregistration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
