# Generated by Django 4.1.5 on 2023-01-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0096_studentregistration_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationcontainer",
            name="num_preps",
        ),
    ]
