# Generated by Django 4.1.5 on 2023-01-24 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0098_alter_unitinquiry_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc),
            ),
            preserve_default=False,
        ),
    ]
