# Generated by Django 4.1.5 on 2023-01-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0099_invoice_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="forgive_date",
        ),
    ]
