# Generated by Django 4.1.9 on 2023-07-22 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0099_invoice_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": (
                    "semester",
                    "-legit",
                    "user__first_name",
                    "user__last_name",
                )
            },
        ),
        migrations.RemoveField(
            model_name="registrationcontainer",
            name="allowed_tracks",
        ),
        migrations.RemoveField(
            model_name="student",
            name="track",
        ),
        migrations.RemoveField(
            model_name="studentregistration",
            name="track",
        ),
    ]
