# Generated by Django 4.1.10 on 2023-07-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0100_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationcontainer",
            name="accepting_responses",
            field=models.BooleanField(
                default=False,
                help_text="Whether responses for this year are being accepted or not.",
            ),
        ),
    ]
