# Generated by Django 4.1.10 on 2023-08-08 16:10

import django.core.validators
from django.db import migrations, models

import roster.models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0101_registrationcontainer_accepting_responses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregistration",
            name="agreement_form",
            field=models.FileField(
                help_text="Signed decision form, as a single PDF",
                null=True,
                upload_to=roster.models.content_file_name,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Decision form",
            ),
        ),
    ]
