# Generated by Django 4.1.10 on 2023-08-10 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roster", "0001_squashed_0102_alter_studentregistration_agreement_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="user",
            field=models.OneToOneField(
                help_text="The Django Auth user attached to the Assistant.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                help_text="The Django auth user attached to the student",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentregistration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
