# Generated by Django 4.2.7 on 2023-12-05 02:44

from datetime import timedelta
from typing import Any

from django.db import migrations
from django.db.models import F


def update_auto_field(apps: Any, scheme_editor: Any):
    UnitInquiry = apps.get_model("roster", "unitinquiry")
    UnitInquiry.objects.filter(
        status__in=("INQ_ACC", "INQ_REJ"),
        updated_at__lt=F("created_at") + timedelta(seconds=5),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0105_unitinquiry_was_auto_processed"),
    ]

    operations = [
        migrations.RunPython(
            update_auto_field, migrations.RunPython.noop, elidable=True
        ),
    ]
