# Generated by Django 5.2.4 on 2025-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0111_alter_studentregistration_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="ad_blurb",
            field=models.TextField(
                blank=True,
                help_text="A text field the instructor can provide if desired.",
            ),
        ),
        migrations.AddField(
            model_name="assistant",
            name="ad_email",
            field=models.EmailField(
                blank=True,
                help_text="An email the assistant can provide for contact.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="assistant",
            name="ad_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the assistant is advertising current availability.",
            ),
        ),
        migrations.AddField(
            model_name="assistant",
            name="ad_url",
            field=models.URLField(
                blank=True, help_text="A URL the assistant can provide if desired."
            ),
        ),
    ]
