# Generated by Django 5.1.9 on 2025-08-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_alter_userprofile_dynamic_progress_and_more"),
        ("roster", "0111_alter_studentregistration_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitinquiry",
            name="target_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="The unit to swap with (only used for swap actions).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swap_inquiries",
                to="core.unit",
            ),
        ),
        migrations.AlterField(
            model_name="unitinquiry",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("INQ_ACT_UNLOCK", "Unlock now"),
                    ("INQ_ACT_APPEND", "Add for later"),
                    ("INQ_ACT_DROP", "Drop"),
                    ("INQ_ACT_LOCK", "Lock (Drop + Add for later)"),
                    ("INQ_ACT_SWAP", "Swap with another unit"),
                ],
                help_text="Describe the action you want to make.",
                max_length=15,
            ),
        ),
    ]
