# Generated by Django 5.2.7 on 2025-11-04 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0112_assistant_ad_blurb_assistant_ad_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyUUID",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        help_text="The UUID for the accepted apply.evanchen.cc application.",
                        unique=True,
                    ),
                ),
                (
                    "percent_aid",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Percentage financial aid requested."
                    ),
                ),
                (
                    "reg",
                    models.OneToOneField(
                        blank=True,
                        help_text="The student registration that cashed in this UUID.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applyuuid",
                        to="roster.studentregistration",
                    ),
                ),
            ],
        ),
    ]
