# Generated by Django 5.2.14 on 2026-06-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0113_applyuuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyuuid",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="If disabled, this UUID cannot be used for registration.",
            ),
        ),
    ]
