# Generated by Django 5.2.16 on 2026-08-02 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0114_applyuuid_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationcontainer",
            name="passcode",
        ),
    ]
