# Generated by Django 5.2.16 on 2026-08-02 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0115_remove_registrationcontainer_passcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentregistration",
            name="processed",
        ),
    ]
