# Generated by Django 6.0 on 2026-08-04 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0116_remove_studentregistration_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyuuid",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
