# Generated by Django 6.0.8 on 2026-08-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0117_applyuuid_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyuuid",
            name="applicant_name",
            field=models.CharField(
                blank=True,
                help_text="The copied application name from apply.evanchen.cc",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="applyuuid",
            name="memo",
            field=models.TextField(
                blank=True, help_text="Any notes about this ApplyUUID."
            ),
        ),
    ]
