# Generated by Django 6.0.8 on 2026-09-02 04:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0120_unitpetition_choice_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 9, 2, 4, 8, 9, 449336, tzinfo=datetime.UTC
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assistant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
