# Generated by Django 6.0.8 on 2026-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0123_student_standing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="forgive_date",
            field=models.DateTimeField(
                blank=True,
                help_text="An extension: the payment is not treated as late until this date.",
                null=True,
            ),
        ),
    ]
